### ISSUE TITLE
No support of train sets with empty classes 

### ISSUE THREAD

**Issue by zjumper1** [berndbischl/mlr#169]
Sometimes empty classes can not be avoided during the training stage. Obviously, this leads to missclasifications. However, it is sad that mlr has no routine to ignore empty classes.
A simple example:
````
library(mlr)
lrn = makeLearner("classif.randomForest")
trainSet = which(iris$Species != "setosa")
train(lrn, iris.task, subset = trainSet)

#Fehler in randomForest.default(m, y, ...) : Can't have empty classes in y.
#Timing stopped at: 0.03 0.01 0.04

**Comment by studerus** [comment]
Can't they be avoided by specifying `stratify = TRUE` in `makeResampleDesc`?

It seems to be dependent on the learner whether empty classes can be dealt with. For example, the above example works with `classif.extraTrees`.

**Comment by jakob-r** [comment]
I think we have to discus here how to deal with that issue...
* Obviously we can just always drop empty factor levels before calling trainLearner...
* We can make this an option somewhere
* We could build a DropEmptyLevelsLearnerWrapper...
* ...

**Comment by jakob-r** [comment]
Okay... we have this method now:
076df4a97c7063c6d1d35eb851f845c3051c4a8f
In train.learner.xxx we can get the task.data by `getTaskData(.task, .subset, recode.target = "drop.levels")`

**Comment by jakob-r** [comment]
I won't drop levels on learners which only give a warning which are
* classif.lda
* classif.nnet
