### ISSUE TITLE
Changing the level of parallelization

### ISSUE THREAD

**Issue by studerus** [berndbischl/mlr#178]
When I parallelize a benchmark experiment using the `benchmark` funktion with 2 learners both of which are tuned using nested cross-validation only 2 cores are used by default. In order to use more than 2 cores, I would like to parallelize the outer loop of the nested cross-validation procedure of the two learners. How can I do that? I tried to set the level argument in `parallelStartSocket` to `resample` but it does not seem to work.

**Comment by berndbischl** [comment]
@studerus 

Can you please check the README of PM and the section in the mlr tutorial on "parallel"
(in the repo not the HTML) 

to make sure it is very clear now?

**Comment by berndbischl** [comment]
@studerus 

Ping. Can you please check?

**Comment by studerus** [comment]
Its much better than before. To really make sure that users do not make the same mistake as I did (forgetting to add `mlr.` to the parallelization level string), I would list the parallelization levels with `mlr.` added to it.

**Comment by berndbischl** [comment]
Add "mlr. " where?

**Comment by studerus** [comment]
In the mlr tutorial on "parallel" at the end of the page where the parallelization levels are described in a list
