### ISSUE TITLE
New paper evaluting the performance 179 classifiers from 17 families 

### ISSUE THREAD

**Issue by studerus** [berndbischl/mlr#190]
In case you didn't see this, there's a [new paper in JMLR](http://jmlr.org/papers/v15/delgado14a.html) in which they assessed the performance of 179 classifiers in 121 data sets. They found that random forest classifiers generally performed best.

I think we could get some inspiration from this paper for deciding which algorithms to implement next.

**Comment by berndbischl** [comment]
We dont need this in the tracker. I will email.
