### ISSUE TITLE
Suggestions for resample()

### ISSUE THREAD

**Issue by shorsch** [berndbischl/mlr#192]
Using a repeated cross validation via resample(), the results include an aggregated performance measure as well as the results in each test set. That is, in a 5 times repeated 10-folded cross validation we can get either the overall measure ($aggr) or 50 values, one for each test set ($measures.test). In some applications one would like to directly get the results for each repeat (here 5 values summing up the performance of each cross validation). Of course it is possible to compute them yourself from the output but it would be nice to get them on a silver platter.  

As I see it, setting setAggregation to testgroup.mean computes the same as test.mean and is therefore needless. Maybe this option could be used to compute the aggregated measures suggested above instead or better additionally to the results in each test set and the overall aggregated measure?

An other point is, that in my opinion the aggregated measures are not accurately computed because the simple average over rates like mmce does not take account for unequal test sample sizes. So a weighted mean should be used. This is especially important in small test sets and computing measures like sensitivity that rely only on a fraction of the test set.
   
Edit: 
Since the performance measures are based on different numerbs of observations (mmce is based on all observations, tpr is just based on those observations with positive class) it might be easier not to weigh the measures resulting from the different cross validation runs but to recompute them for each repeat as well as for the aggregated measure (although a simple mean over the repeats would also give accurate over all measures). Otherwise the weights would need to be different depending on the performance measure.

**Comment by shorsch** [comment]
Bernd asked for the code I am using right now to overcome this problem. At the moment I am extracting the relevant information (especially the computed probabilities for a positive status and the true status) from the registry and calculate the performance measures from that.
So I am starting with the registry and since I made a benchmark study with r replications, s tasks and l learners, I want a dataframe containing the performance measures for each combination of replications, tasks and learners  as a final result.

```library(ROCR)

# In order to calculate the performance measures, aggregated for each 
# replication, the probabilities for a positive status are extracted from the
# registry (for each prediction that was done).
# If you did a benchmark study with an overall sample size of n (distributed 
# over s tasks), r replications and l learners that will be n*r*l probabilities.


collector<- function(job, res){
  vorhers<- res$pred
  
  # what are the names for the positive and negative status
  krank  <- vorhers$task.desc$positive 
  gesund <- vorhers$task.desc$negative 
  # probability for a positive status
  p.krank<- do.call("$", list(vorhers$data, paste("prob.", krank, sep="")))
  
  return(list(id = job$id,
           # information about the corresponding experiment    
           prob = job$prob.id,
           algo = job$algo.id,
           repl = job$repl,
           # necessary information for the calculation of the performance measures
           truth= vorhers$data$truth,
           response=vorhers$data$response,
           p.krank=p.krank,
           krank=krank,
           gesund=gesund))   
}

# Extract the information from the registry (called reg)
reduce.info<- reduceResultsList(reg, fun = collector)

# Create a dataframe, containing all information (n*r*l rows)
pred<- do.call(rbind, lapply(reduce.info, function(x){
  n<- length(x$truth)
  data.frame(id=rep(x$id, n), repl=rep(x$repl,n), 
             algo=rep(x$algo, n), task=rep(x$prob, n),
             krank=rep(x$krank, n), gesund=rep(x$gesund, n),
             truth=x$truth, response=x$response, p.krank=x$p.krank)
}))

# Define a character vector with performance measures that are supported by performance() 
masse=c("sens", "spec", "ppv", "npv", "acc", "auc")

# write a function for calculating the desired performance measures; 
# requires vectors as input:
# probs: probabilities for positive status
# truth: true status
# label.ordering (2-dim. character-vector with the names of negative and positive 
#                 status one after another)
# masse: character-vector with the desired performance measures
# Output: Vector containing the calculated performance measures
masse.all<- function(probs, truth, label.ordering, masse){
  # in case there were errors and the registry does not contain the relevant info
  if(all(length(truth)==0)){return(rep(NA, length(masse)))}
  # Create a prediction-object (package: ROCR)
  pred<- prediction(predictions=probs, labels=truth, label.ordering=label.ordering)
  
  erg.reps<- as.data.frame(t(apply(as.matrix(masse), 1, function(m){
    # Calculates the measure usually for all cutpoints (of course not for e.g. AUC)
    perf.m<- performance(pred, measure=m)
    # Choose measure for the smalles cutpoint bigger than 0.5
    # (except there is just one like AUC, then the single result is returned)
    # (there might be smarter ways to do that but somehow I couln't find a function that 
just 
        calculates the measures for the 0.5 cutpoint) 
    if(length(perf.m@x.values) > 0){
      data.perf.m<- data.frame(x=perf.m@x.values[[1]],y=perf.m@y.values[[1]])
      sort.data.perf.m<- data.perf.m[order(data.perf.m$x),]
      return(sort.data.perf.m[match(1, sort.data.perf.m$x>=0.5),2])
    }else{
      return(perf.m@y.values[[1]])
    }
  })))
  names(erg.reps)<- masse
  return(erg.reps)
}

# Calculate the measures seperated for replication, task and learner
masse.rep<-  lapply(split(pred, list(pred$repl, pred$task, pred$algo)), function(z){
  masse.all(probs=z$p.krank, truth=z$truth, label.ordering=c(as.character(unique(z$gesund)),
                                                              as.character(unique(z$krank))), 
             masse=masse)})

# Create the final dataframe, containing the measures and the information, 
# which task, which learner and which replication they belong to
# (r*l*s rows)
repli<- unlist(lapply(strsplit(names(masse.rep), ".", fixed=T), function(x)x[1]))
task<- unlist(lapply(strsplit(names(masse.rep), ".", fixed=T), function(x)x[2]))
algo<- unlist(lapply(strsplit(names(masse.rep), ".", fixed=T), function(x)x[3]))
masse.df<- do.call(rbind, masse.rep)
masse.df$task<- task
masse.df$algo<- algo
masse.df$repli<- repli```

**Comment by mllg** [comment]
With 5064c7003671bfe45a54a060f79872abbb112276 we now use a weighted mean in `testgroup.mean`. 

@berndbischl please review.

**Comment by berndbischl** [comment]
@shorsch 

Could you please check if test.join is OK for you and does what you want?
then please close.

**Comment by shorsch** [comment]
test.join is great and does what I want, thank you! 
There is no option to get the results for each replication, right? You can choose to get the results for each test set or alternatively the overall result, right? That's fine I just wanted to make sure I didn't miss this.
When I built an example to demonstrate the difference between test.join and testgroup.mean I found that you changed testgroup.mean, too by including weights. I actually thought, you didn't want the weights there- especially because they would not be correct for measures like sensitivity or specifity.
Maybe you want to check this again and remove the changes in case I am right.

**Comment by berndbischl** [comment]
@shorsch 
> There is no option to get the results for each replication, right?

No, decided not to add a helper just for that. Complain again if it really hurts.

@mllg 
> you changed testgroup.mean, too by including weights

Can you please remove this again, then close?
