### ISSUE TITLE
Possibility to set parameters outside a given range

### ISSUE THREAD

**Issue by shorsch** [berndbischl/mlr#216]
Is there a chance to set a parameter in makeLearner to a value that is not in the given range?

Example: 
The parameter ct in makeRLearner.classif.ada has to take a value between 0 and 1. Usually, this is a reasonable restriction but I recently found an application in the package description, where I should set it to -1. Actually, in this particular case I am not sure yet, if 0 wouldn't do the same thing, but in general there might be situations where you want to do things that don't seem right at first glance.
Maybe there could be a function similar to configureMlr(on.par.without.desc = "quiet") just for already implemented parameters.

**Comment by mllg** [comment]
Should be fixed in cb2e7028ed08ebe9c1ee449db141ccc076b6b594 and da313a65588b9dc1961f9481b39caea2f5f62fe1.

@berndbischl Do we want to allow `cp == -1` for rpart, too?

**Comment by shorsch** [comment]
Great! Right, the cp-Parameter is actually for rpart, so it would have to be changed there, too.

**Comment by berndbischl** [comment]
I currently see why cp should be -1. So I will revert this. With par.out.of.bounds you can now disable this check, if you really want.

But before I allow neg. values I would really like to see an argument why this is needed. 0 seems to do exactly the same.

**Comment by berndbischl** [comment]
For reference, more info is here
/http://cran.r-project.org/web/packages/rpart/vignettes/longintro.pdf

**Comment by berndbischl** [comment]
I guess we can close this. @mllg implemented what we need.
