### ISSUE TITLE
Questions about threshold tuning

### ISSUE THREAD

**Issue by schiffner** [berndbischl/mlr#222]
I have some more questions about threshold tuning.
I don't mean to be pushy, so if you are still working on it, just ignore/delete/close this.

1. How am I supposed to use the optimal threshold after tuning?
   The optimal learner parameters are in `$x` of the tuning result, the only way that I see
   to extract the optimal threshold is from the `$opt.path`.
  
2. I played around with the tuneWrapper, threshold tuning and nested resampling.
   I would have expected the tuneWrapper to use the optimal threshold for predictions in the
   outer loop, but this is not the case.
   (Here is an example, sorry it's so long, I had to construct one where threshold tuning really makes a difference.)

```
lrn = makeLearner("classif.lda", predict.type = "prob")
rdesc = makeResampleDesc("Holdout")
rin = makeResampleInstance(rdesc, sonar.task)
costs = matrix(c(0, 5, 1, 0), 2)
colnames(costs) = rownames(costs) = getTaskDescription(sonar.task)$class.levels
sonar.costs = makeCostMeasure(id = "sonar.costs", costs = costs, task = sonar.task, best = 0,
  worst = 5)
ps = makeParamSet(
  makeDiscreteParam("method", "moment")
)
ctrl1 = makeTuneControlGrid(tune.threshold = TRUE)
ctrl2 = makeTuneControlGrid(tune.threshold = FALSE)
lrn1 = makeTuneWrapper(lrn, resampling = rdesc, measures = list(sonar.costs, mmce), par.set = ps, control = ctrl1)
lrn2 = makeTuneWrapper(lrn, resampling = rdesc, measures = list(sonar.costs, mmce), par.set = ps, control = ctrl2)
r1 = resample(lrn1, sonar.task, resampling = rin, measures = list(sonar.costs, mmce), extract = getTuneResult)
r2 = resample(lrn2, sonar.task, resampling = rin, measures = list(sonar.costs, mmce), extract = getTuneResult)

r1
Resample Result
Task: Sonar-example
Learner: classif.lda.tuned
sonar.costs.aggr: 0.73
sonar.costs.mean: 0.73
sonar.costs.sd: NA
mmce.aggr: 0.33
mmce.mean: 0.33
mmce.sd: NA

r2
Resample Result
Task: Sonar-example
Learner: classif.lda.tuned
sonar.costs.aggr: 0.73
sonar.costs.mean: 0.73
sonar.costs.sd: NA
mmce.aggr: 0.33
mmce.mean: 0.33
mmce.sd: NA
```

3. If I would like to plot the learner prediction with and without thresholding, just to see
   how decision borders change through thresholding. How can I do that?
  
   I can see how this would work with a tuneWrapper, but not how to do this with a fixed threshold.
   Do you plan to bring back the threshold wrapper?

**Comment by berndbischl** [comment]
1) It is stored in TuneResult and FeatSelResult now

**Comment by berndbischl** [comment]
3) Please open up a separate issue. Will do later

**Comment by berndbischl** [comment]
2) Fixed and unit tested.

Can you please mentioned the  changed stuff from this thread in the tutorial, then close?

**Comment by schiffner** [comment]
3) works when you use the `predict.threshold` argument of `makeLearner`.

**Comment by berndbischl** [comment]
@schiffner 

I am not sure what the status is here now? Do you simply need to mention a few lines in the tutorial?

**Comment by schiffner** [comment]
1) and 2) will be mentioned in the tutorial, maybe also an example for 3) and maybe there will be a new section about thresholding. I will sort this out tomorrow or Wednesday and then close. 
Regarding 3) I am not sure. You asked me to open another issue, but now that I'm aware of the predict.threshold option in makeLearner I'm not sure if the threshold Wrapper is needed. What do you think?

**Comment by berndbischl** [comment]
tutorial: Thx.

> Regarding 3) I am not sure. You asked me to open another issue, but now that I'm aware of the 
> predict.threshold option in makeLearner I'm not sure if the threshold Wrapper is needed. 
> What do you think?

The thresholdWrapper is now definitely not needed IMHO. And if the plot works for you it is fine for me.
I mean, from my side I dont see a problem. Tell me, if there is one for you.

**Comment by schiffner** [comment]
Don't think so, no problem in sight at the moment.
