### ISSUE TITLE
classif.kknn {kknn} 

### ISSUE THREAD

**Issue by SarahSunshine** [berndbischl/mlr#226]
Since updating to latest mlr version (2.3) issues appear when using classif.kknn on classification tasks that contain factor input variables: 

data(iris)

### Duplicate feature `Species´ to add a factor input variable to iris.task
iris_modif <- data.frame(Species2 = iris$Species, iris)

task <- makeClassifTask(data = iris_modif, target = "Species")

### Define k-nearest neighbor classificator, k = 4
lrn <- makeLearner("classif.kknn", k = 4)

### Define resampling
rdesc <- makeResampleDesc("Holdout")

### Simple benchmark experiment
res <- benchmark(tasks = task, learners = lrn, resampling = rdesc, show.info = TRUE)

**Comment by berndbischl** [comment]
This is a problem in kknn, This shows it. Same bug:

```
requireNamespace("kknn")
d = data.frame(Species2 = iris$Species, iris)
m = kknn::kknn(Species~., train = d, test = d)
```

Same error.

**Comment by berndbischl** [comment]
What I am doing now:

1) load kknn explicitly into the gobal NS, that fixes this.

2) I have notified Uwe L.  about this, as I dont even know what to tell the kknn maintainer, how to fix this.

3) Adding a unit test now for all learners that claim to support factors

**Comment by berndbischl** [comment]
Did what I said. Fixed.
