### ISSUE TITLE
normalizeFeatures : Docs

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/mlr#227]
Please be a bit more specific what each method does on the help page.

**Comment by Autodidact24** [comment]
Hi @berndbischl @jakob-r,
I'm new to mlr. I would like to contribute. I can take up this task. I do have some experience of using Python libraries for feature scaling and normalization.

Thanks,
Shubham

**Comment by berndbischl** [comment]
Hi and thanks.

In general: Please provide a pull request. 
(Although we might close this one very soon as it is so tiny)

If you want to help as a regular member, please send us an email with background info.
