### ISSUE TITLE
Tutorial: Strange note

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/mlr#232]
In section "Performance"

```
lrn = makeLearner("cluster.kmeans", centers = 3)
mod = train(lrn, mtcars.task)
pred = predict(mod, task = mtcars.task)

## Calculate the Dunn index
performance(pred, measures = dunn, task = mtcars.task)

#> Note: the specification for class "numeric or NULL" in package 'clValid' seems equivalent to one from package 'SparseM': not turning on duplicate class definitions for this class.

```

**Comment by jakob-r** [comment]
Not there anymore. Maybe it's something local on your building machine. Reopen if it shows up again.

**Comment by berndbischl** [comment]
It is triggered by loading clValid in measure "dunn"

Suppressing messages resolves this.

**Comment by berndbischl** [comment]
I could also not reproduce this outside of the tutorial.

I guess you have to load packages in the right order to trigger this. Sigh.

I am suppressingMessages now for the require call to clValid
