### ISSUE TITLE
cluster measure dunn (and maybe others) dont work when only 1 cluster is produced

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/mlr#237]
set.seed(2)
rdesc = makeResampleDesc("Subsample", iters = 5, split = 4/5)
r = resample("cluster.XMeans", mtcars.task, rdesc, measures = list(dunn, db, timetrain))

Resample] subsampling iter: 4
Error in min(interClust, na.rm = TRUE) : 
  (converted from warning) no non-missing arguments to min; returning Inf

**Comment by larskotthoff** [comment]
In principle I would say that this is a bug in the upstream package, but at least dunn index doesn't make sense if there's only one cluster. Do we want to handle this explicitly in mlr?

**Comment by berndbischl** [comment]
I dont know, but we already had this problem in the tutorial and I dont want these warnings there.

mlr's task is to make the users life easier. At there least we need a useful error message IMHO

**Comment by larskotthoff** [comment]
It seems to me that it's the same fundamental issue as in #226 (bug in upstream package). While I agree with you that it would be good to have mlr do something better, it can't be our task to work around bugs in other packages.

**Comment by berndbischl** [comment]
#226 is actually a bit different, because nobody in R seems to check whether package work when they are loaded via requireNamespace....

**Comment by berndbischl** [comment]
And regarding dunn: I dont think this is really a bug. I guess the formula is simply "undefined" for single clusters. So we simply need a better error message or a better result value. 

mlr contains now one million of these use ability enhancements, thats why the package is so useful.

**Comment by larskotthoff** [comment]
Hmm, are you sure that there's only a single cluster? When I look at the predictions passed to the dunn index function I see always 2 (still get the warning though).

**Comment by berndbischl** [comment]
@larskotthoff 

Can you please post your example?

**Comment by larskotthoff** [comment]
Same as yours. I've printed out the clusters during resampling and get always at least two, but the same warning. So it doesn't appear to be related to the number of clusters.

**Comment by berndbischl** [comment]
I mean, the example has a seed?

I am seeing this:

```
[Resample] subsampling iter: 1
 num [1:7] 2 1 2 2 2 2 1
NULL
[Resample] subsampling iter: 2
 num [1:7] 2 4 4 3 2 1 4
NULL
[Resample] subsampling iter: 3
 num [1:7] 2 2 1 2 2 2 1
NULL
[Resample] subsampling iter: 4
 num [1:7] 1 1 1 1 1 1 1
NULL
[Resample] subsampling iter: 5
 num [1:7] 2 2 2 1 2 1 2
NULL
```

**Comment by berndbischl** [comment]
These are the clusters, printed from inside the call of measure dunn. Iter 4 is constant

**Comment by larskotthoff** [comment]
I'm getting the same with more than one cluster:

>  res = resample("cluster.XMeans", mtcars.task, rdesc, measures = list(dunn, db,
 timetrain))  
[Resample] subsampling iter: 1
 num [1:7] 1 2 2 2 1 2 1
NULL
[Resample] subsampling iter: 2
 num [1:7] 4 4 4 4 2 3 4
NULL
[Resample] subsampling iter: 3
 num [1:7] 2 3 1 2 1 3 2
NULL
[Resample] subsampling iter: 4
 num [1:7] 2 4 4 4 4 4 1
NULL
[Resample] subsampling iter: 5
 num [1:7] 2 1 1 1 1 1 2
NULL
[Resample] Result: dunn.test.mean=0.423,db.test.mean=0.527,timetrain.test.mean=0
.0428
Warning messages:
1: In max(distance[c1, c1]) :
  no non-missing arguments to max; returning -Inf
2: In min(distance[c1, c2]) :
  no non-missing arguments to min; returning Inf
3: In min(distance[c1, c2]) :
  no non-missing arguments to min; returning Inf
4: In min(distance[c1, c2]) :
  no non-missing arguments to min; returning Inf
5: In max(R[i, ][is.finite(R[i, ])]) :
  no non-missing arguments to max; returning -Inf
6: In min(distance[c1, c2]) :
  no non-missing arguments to min; returning Inf
7: In min(distance[c1, c2]) :
  no non-missing arguments to min; returning Inf
8: In max(distance[c1, c1]) :
  no non-missing arguments to max; returning -Inf
9: In min(distance[c1, c2]) :
  no non-missing arguments to min; returning Inf
10: In max(R[i, ][is.finite(R[i, ])]) :
  no non-missing arguments to max; returning -Inf

I'm getting this for different seeds, different numbers of error messages. Sometimes it works fine. But it seems pretty clear that it's not related to the number of clusters.

**Comment by berndbischl** [comment]
Ok, so WEKA does not respect the R seed right?

**Comment by berndbischl** [comment]
If i run this again and again it is always the same...?

**Comment by berndbischl** [comment]
But with set.seed(5) I have your case, different clusters and the warning.....

**Comment by larskotthoff** [comment]
Yes, same here. I tried different seeds as well.

**Comment by berndbischl** [comment]
I have debugged his inside clValid. The problem occurs when one cluster is EMPTY

**Comment by larskotthoff** [comment]
Hmm, is this something we should check/fix in the clusterer?

**Comment by berndbischl** [comment]
No it is in the measure
I can fix it like this

```
    r = pred$data$response
    r = as.integer(as.factor(r))
    print(r)
    clValid::dunn(Data = feats, clusters = r)
```

Now I tsill get warnings, but a "dunn value"

**Comment by larskotthoff** [comment]
That's the same I got, but I thought this was about the warnings?
