### ISSUE TITLE
do not call gc.reset in tune logger

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/mlr#239]
This changes an internal "state" that the user cannot undo later. Maybe he wants to see maxmem consumption.

**Comment by berndbischl** [comment]
Can we do this:

simply call gc and report in logging: current mem + maxmem?

I know this is different what you  @mllg  wanted, but there is no way in R to do that, that I know, without gc reset.

We could doc what the logger does, then it is clear and still somewhat useful.

**Comment by berndbischl** [comment]
ok mllg accepted

**Comment by berndbischl** [comment]
@mllg 
Could you please review this and run a quick example to see if you think it is ok?

**Comment by mllg** [comment]
Looks good.
