### ISSUE TITLE
tutorial "Visualizing the prediction" correct?

### ISSUE THREAD

**Issue by aydindemircioglu** [berndbischl/mlr#241]
In http://berndbischl.github.io/mlr/tutorial/html/predict/index.html it is stated that

"For classification, we get a scatter plot of 2 features (by default the first 2 in the data set). The type of symbol shows the true class labels of the data points. The color indicates if observations are misclassified."

is it the color or this 'double line' of the symbol that indicates misclassification?
additionally stating that more saturated colors means higher probability (i assume?) might be helpful.

**Comment by Autodidact24** [comment]
@aydindemircioglu 
+1. The colors just indicate the decision boundaries (or regions) of the classes after classification. Its the 'double line' for points that indicate misclassification.

**Comment by berndbischl** [comment]
You guys are right.

@schiffner 
Can you quickly update these 1-2 sentences please?

**Comment by schiffner** [comment]
Yep, you are right. (These sentences stem from a time where misclassified points were yellow by default.)
Thanks for pointing this out.

**Comment by schiffner** [comment]
I am very sorry for the delay. It's fixed now.
Thanks again.
