### ISSUE TITLE
predict.threshold argument of makeLearner

### ISSUE THREAD

**Issue by schiffner** [berndbischl/mlr#244]
Below I specify a threshold via `predict.threshold` in `makeLearner` without setting `predict.type = "prob"`. Shouldn't we return some warning/error or maybe, for full service, automatically set the predict.type to "prob" internally if a threshold is given?

```
th = c(setosa = 1, virginica = 4, versicolor = 8)
lrn = makeLearner("classif.lda", predict.threshold = th)
mod = train(lrn, task = iris.task)
pred = predict(mod, task = iris.task)
pred

Prediction: 150 observations
predict.type: response
threshold: 
time: 0.00
  id  truth response
1  1 setosa   setosa
2  2 setosa   setosa
3  3 setosa   setosa
4  4 setosa   setosa
5  5 setosa   setosa
6  6 setosa   setosa
```

**Comment by berndbischl** [comment]
You are right. But I rather have the more verbose option where one is forced to set the type, so your case will be an error.

**Comment by schiffner** [comment]
Ok. Thanks.
