### ISSUE TITLE
Error in selectFeatures when using tune.threshold (iris.task)

### ISSUE THREAD

**Issue by phASL** [berndbischl/mlr#246]
selectFeatures returns an error when setting tune.threshold = TRUE.

At first, setting tune.threshold = FALSE, which works fine:

```R
library("mlr")
rdesc = makeResampleDesc("Holdout")
lrn = makeLearner("classif.lda", predict.type = "prob")

ctrl = makeFeatSelControlSequential(method = "sfs", tune.threshold = FALSE)
set.seed(1909)
sfeats = selectFeatures(learner = lrn, task = iris.task, resampling = rdesc, control = ctrl,
                        show.info = FALSE)
sfeats
# FeatSel result:
# Features (2): Sepal.Width, Petal.Width
# mmce.test.mean=0.04
```

Now setting tune.threshold = TRUE:
```R
ctrl2 = makeFeatSelControlSequential(method = "sfs", tune.threshold = TRUE)
set.seed(1909)
sfeats2 = selectFeatures(learner = lrn, task = iris.task, resampling = rdesc, control = ctrl2,
                         show.info = FALSE)
# Error in e$extra[[index]] : subscript out of bounds
```

I guess that the error occurs at this line of code in the ParamHelpers:::getOptPathEl.OptPathDF function:
https://github.com/berndbischl/ParamHelpers/blob/de485142be805f38d4f030b6acebc41a07e28688/R/OptPathDF_getter.R#L31

This function is called from mlr:::makeFeatSelResultFromOptPath:
https://github.com/berndbischl/mlr/blob/60f37b1477fd28e04d15870d6ff07c8a6c9b7e81/R/FeatSelResult.R#L50

And this is called from mlr:::selectFeaturesSequential here:
https://github.com/berndbischl/mlr/blob/2e0eb94cd83e453e37441c45f3d236a9f96d56bc/R/selectFeaturesSequential.R#L106

I think it's a problem with some mlr code, that's why I opened the issus in this repository. I hope it's ok?

BTW: I am surprised that this error doesn't occur with sonar.task (see #245)...

**Comment by berndbischl** [comment]
I guess I found the error. It seems to be a bug in seqFS, in combo with tune.threshold. 
The threshold of the first iteration (empty set) is not stored, it seems.

**Comment by berndbischl** [comment]
fixed
