### ISSUE TITLE
Improvements in plotROCRCurves

### ISSUE THREAD

**Issue by schiffner** [berndbischl/mlr#247]
Some things I noticed when writing the tutorial. 

  * Defaults:
  
    1. The default is `avg = "threshold"`. That does not make much sense if `obj` is a (`list` of)
       `Prediction` objects. The default should depend on `obj`. In my opinion we should set `avg = "none"` for (`list`s of) `Prediction` objects and `avg = "threshold"` for (`list`s of) `ResamplePrediction` objects and `BenchmarkResult`s.

    2. The colored boxes in the legend are not needed. Therefore keep `fill = NULL` (the default in
       `legend`).

    3. The default is `add.diag = TRUE`: The diagonal does only make sense for ROC curves
       and it's tedious to set is to `FALSE` when plotting other performance measures.
       Maybe the default should be `FALSE` or depend on `meas1` and `meas2`.

  * At the moment standard `plot` arguments like `xlab` or `ylim` cannot be used.
    Many graphical options of ROCR's `plot` function also do not work.
    Either give `plotROCRCurves` a `...` argument or something like `plot.args` to pass
    graphical parameters.

  * Determine `ylim` internally to prevent the following:

    ```
    lrn1 = makeLearner("classif.lda", predict.type = "prob")
    mod1 = train(lrn1, sonar.task)
    pred1 = predict(mod1, task = sonar.task)
    
    lrn2 = makeLearner("classif.ksvm", predict.type = "prob")
    mod2 = train(lrn2, sonar.task)
    pred2 = predict(mod2, task = sonar.task)

    plotROCRCurves(list(lda = pred1, ksvm = pred2), meas1 = "acc", meas2 = "cutoff", avg = "none",
      add.diag = FALSE, legend.args = list(x = "bottom"))
    ````

**Comment by zmjones** [comment]
about ii. do you mean the boxes around the colors inside the legend, or the box around the legend itself? in the former case this can be controlled using `fill` and `border` but in the latter case `bty = "n"` removes the box.

**Comment by schiffner** [comment]
@zmjones: I mean the colored boxes inside the legend. There is no need for them, as there are only colored lines in the plot.
Thanks very much!

**Comment by schiffner** [comment]
I updated i. (default `average` setting) in the first post:
In my opinion we should set `average = "none"` for (`list`s of) `Prediction` objects and `average = "threshold"` for (`list`s of) `ResamplePrediction` objects and `BenchmarkResult`s.
@berndbischl @larskotthoff: OK, or would you prefer a different solution?

**Comment by larskotthoff** [comment]
@schiffner Sounds good. It would also be nice to have documented in more detail what `avg` does.

**Comment by zmjones** [comment]
ok @schiffner i updated #259 with those changes. i also reordered the file a bit and updated news. do you agree that `bty = "n"` looks nicer (no box around the legend)? 

master appears to be failing `check()` but i don't think i've broken anything. 

also, after this is merged i can update the tutorial as well. 

@larskotthoff i haven't added to the docs for `avg` other than to note what the new defaults are. would you prefer that we have the documentation ourselves, or could we just link to the documentation for `ROCR::plot` where they describe it in detail?

**Comment by larskotthoff** [comment]
@zmjones No need to duplicate anything, but the pointer to the documentation should certainly be there.

**Comment by zmjones** [comment]
ok, i linked `\code{\link[ROCR]{plot-methods}}`
