### ISSUE TITLE
Error: could not find function "getTaskSize"

### ISSUE THREAD

**Issue by seanlao** [berndbischl/mlr#248]
Code:

data(BreastCancer, package = "mlbench")
df = BreastCancer
df$Id = NULL
classif.task = makeClassifTask(id = "BreastCancer", data = df, target = "Class")
getTaskSize(classif.task)

ERROR:

Error: could not find function "getTaskSize"

Although I can use [classif.task$task.desc$size] instead.

getTaskSize: introduced as "n = getTaskSize(bh.task)" in http://berndbischl.github.io/mlr/tutorial/html/bagging/

**Comment by schiffner** [comment]
getTaskSize is a new function introduced in mlr 2.3. I guess you just need to update your mlr installation.

**Comment by ceekr** [comment]
I am on 2.3 and it still shows the error. Here is my console dump:

> packageVersion("mlr")
[1] ‘2.3’
> n <- getTaskSize(wnv.task)
Error: could not find function "getTaskSize"
> 

R version is:

Revolution R Open 3.2.0
Using CRAN snapshot taken on 2015-05-01
The enhanced R distribution from Revolution Analytics
Visit mran.revolutionanalytics.com/open for information
about additional features and technical support options.

Re-open ticket?

**Comment by larskotthoff** [comment]
Did you load the mlr library? Works fine for me (although I'm not sure where you're getting `wnv.task` from):

    > library(mlr)
    > getTaskSize(bh.task)
    [1] 506

**Comment by ceekr** [comment]
hmm, strange indeed. Here is my snippet:

> library("mlr")
> ## Make learning task
> wnv.task <- makeClassifTask(data = dfTrain.fit, target = "WnvPresent", positive = 1)
> n <- getTaskSize(wnv.task)
Error: could not find function "getTaskSize"
> packageVersion("mlr")
[1] ‘2.3’

**Comment by jakob-r** [comment]
If it's not a too big hazzle try the newest version from cran by calling `install.packages("foreign")`. Maybe you got a version from github before we introduced `getTaskSize` but already had the Version on 2.3.
Please tell me if it worked.

**Comment by berndbischl** [comment]
I just checked
@jakob-r Introduced the function on 09Feb, mlr2.3 went on CRAN on 04Feb. This is also stated in the NEWS file, that is why we have it. 

So I guess @schiffner just made an error, when she said "it was introduced in 2.4".
Sorry :) 

So just update the package to cran release 2.4, and it is there.

Close?

**Comment by schiffner** [comment]
I'm sorry for the typo and the confusion it caused. :( Thank you all for figuring it out.

**Comment by berndbischl** [comment]
That happens. I guess what we discussed wrt to the versioning of the tutorial will also help here.

Closing

**Comment by berndbischl** [comment]
Ah, well it was already closed :)

**Comment by ceekr** [comment]
Great - thanks guys for getting to this quickly! Appreciate it.
