### ISSUE TITLE
Query regarding GSOC - 2015 Projects

### ISSUE THREAD

**Issue by rishy** [berndbischl/mlr#249]
Hey Everyone,

I am Rishabh, a GSOC participant for the year 2015 and an aspiring Data Scientist(just to sound a bit cooler ;) ).
I was going through 'rstats-gsoc' page and saw 'mlr' among the projects. I was really intrigued by the idea of having a standard implementation structure for all ML algorithms and 'mlr' is doing a great job for that.

I am particularly interested in "Improving mlr's hyperparameter and tuning system for efficient model selection" and "Implementing several ensemble SVMs in mlr". I think in past I might have used 'mlr' maybe once or twice while I was starting with R. 

Although it was suggested on 'mlr' ideas page that I can start with implementing a new Learner, are there any other particular issues that I can start with? Also is there a wiki about 'contribution guidelines' in 'mlr' repo, so I can continue with already existing coding standards for 'mlr'?

I had to create this issue because my request is still pending at 'gsoc-r' google group and I also saw that 'you guys don't hate beginners' bugging you with questions in Github Issues ;).

**Comment by berndbischl** [comment]
GSOC has already begun.
