### ISSUE TITLE
GSOC 2015 Global thread!

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/mlr#252]
Post questions and comments about our google summer of code projects here.

**Comment by rishy** [comment]
Hey Everyone,

I am Rishabh, a GSOC participant for the year 2015 and an aspiring Data Scientist(just to sound a bit cooler ;) ).
I was going through 'rstats-gsoc' page and saw 'mlr' among the projects. I was really intrigued by the idea of having a standard implementation structure for all ML algorithms and 'mlr' is doing a great job for that.

I am particularly interested in "Improving mlr's hyperparameter and tuning system for efficient model selection" and "Implementing several ensemble SVMs in mlr". I think in past I might have used 'mlr' maybe once or twice while I was starting with R. 

Although it was suggested on 'mlr' ideas page that I can start with implementing a new Learner, are there any other particular issues that I can start with? Also is there a wiki about 'contribution guidelines' in 'mlr' repo, so I can continue with already existing coding standards for 'mlr'?

**Comment by rishy** [comment]
Hi @berndbischl ,

I was having a look at the available learners in 'mlr'. I think we still don't have Generalized Additive Models in 'mlr'. I'd like to start implementing it using 'mgcv' package. Just wanted to make sure that someone else is already not working on that.

There are a couple of other (not so frequently) used learners like:
                - Regularized random forest
		- Relaxed lasso
		- Bagged CART, etc.

I am hoping to get done with these as well. I'll fill you in regarding the progress.

**Comment by aydindemircioglu** [comment]
@rishy:
hi rishabh, the test for the ensemble svm project is finalized now, if you want to implement that directly as a learner in mlr, feel free to do so (though i am not sure if bernd wants this in mlr ;)).

**Comment by rishy** [comment]
@aydindemircioglu, I think I'll start developing it directly as a learner in mlr, and send the PR. Where it can lie happily for a while, until Bernd decides to merge it with mlr ;). 

Other than that I am also pretty much interested in "improving mlr's hyperparameter..." project. I thought I will start with implementing at least one of the above mentioned learner just to get familiar with the mlr codebase. So, have you guys already decided on test for this project?

**Comment by aydindemircioglu** [comment]
@rishy i think we decided that everything that is specific to the three mlr projects should go here, everything more general to the google groups.

**Comment by berndbischl** [comment]
Also the #257

**Comment by sarunasmerkliopas** [comment]
Hey there,

I just want to clarify the general application scheme to do things right. 

I am particularly interested in participating in [Improving mlr's visualisations](https://github.com/berndbischl/mlr/wiki/GSOC-2015:-Improving-mlr's-visualisations) project and it has a test that I should try to do. On the other hand, on the 'main' page ([mlr GSOC 2015 Proposal](https://github.com/berndbischl/mlr/wiki/mlr-GSOC-2015-Proposal)) there is a note that should send the info about myself to the mentors. So I was just wondering whats the sequence? I mean will it be sufficient that I do the test and provice my application (info about myself) through Melange? Or should I first do the test, provide info and only then fill Melange's application for it to be considered?

Thanks!

**Comment by larskotthoff** [comment]
@sarunasmerkliopas Any sequence is fine. I would provide the information first.

**Comment by dhruvil-patel** [comment]
Hey there, 

I am Dhruvil, currently pursuing Masters in Computer Science at IIIT-Hyderabad. I have sufficient backgroung knowledge of machine learning as well as R. 

I am interested in [Implement several ensemble SVMs in mlr](https://github.com/berndbischl/mlr/wiki/GSOC-2015:-Implement-several-ensemble-SVMs-in-mlr) and also completed Test task with [R code](https://github.com/dhruvil-patel/mlr/blob/master/R/RLearner_classif_ensemble_svm.R) 
using mlr package. 

I was wondering what should i do next ? Implement the Learner for the same in mlr or something else.

Thanks.

**Comment by aydindemircioglu** [comment]
@dhruvil-patel 
thanks for the code, i'll take a closer look at it in a few days.
i think the most important thing is the proposal.
it might be that the scope of the ensemble project is too little,
so try to find a direction you want to go after the three ensembles 
are  implemented.

**Comment by rishy** [comment]
Hey Everyone, 

I have just implemented a "Generalized Additive model for Classification". I have also added a corresponding unit test for the same. But I am having some issues with running testthat tests.
Should running devtools::check() from the root of the repo is going to enough to test that I am not breaking anything? 

Or is there any other approach you guys prefer for testing?

**Comment by larskotthoff** [comment]
@rishy You can open a pull request and travis will check automatically. You can also run `test_all.R` in the root directory to run all the tests.

**Comment by arinik9** [comment]
Hello everyone,

I am Nejat ARINIK. I am currently a senior at the University of Galatasaray, Istanbul majoring in Computer Science. At the same time, I will keep going the Double
Degree’s Program, is equivalent to the master 2, at the National Institute of Applied Sciences in Lyon, France next year. I am delighted to hear about the projects proposed by gsoc-r and I'am interested in the project Implement several ensemble SVMs in mlr.

I have good knowledge of Machine Learning as well as R. I have also implemented Machine Learning algorithms before as part of my course work and I've realized the majority of programming exercices. On the other hand, this year my senior  project is based on complex networks, community detection and pattern mining. For this purpose, I'm using R language with some package, especially igraph. 

As mentioned in the project listing I have implemented the test task in R using mlr. Please find the code [here](https://github.com/arinik9/mlr/blob/master/R/Rlearner_kmeans_svm.R) and the [link](https://github.com/arinik9/mlr/blob/master/R/Rlearner_kmeans_svm_test.R) of main file (is not a test file in fact, just for executing the function). In the test task, I've wanted to practice more my knowledge about mlr. Then, I added two user-friendly features: Optimazing the parameters if user didn't enter them and using the possibility of the datasets non-binary (like iris dataset).  In the code, I've tried to explain what I did. And I am wondering if my prediction method works well or something else wrong? How can I test it? I would appreciate a feedback if possible.

I am simultaneously working on the proposal. Should I send the first draft of my proposal via gsoc-r google groups? Would it be a good idea if I create google document for the draft version?

Awaiting your reply.
Thanks.

**Comment by berndbischl** [comment]
Hi, for all the guys from the R project (who will select proposals in the end) we have out up a wiki page to describe our mentor team. 
Maybe you also find this helpful.

https://github.com/berndbischl/mlr/wiki/GSOC-2015:-Your-Mentors

**Comment by aydindemircioglu** [comment]
@arinik9 

dear nejad,

thanks for your interest in the ensemble svm project and your code. 

i just skimmed over the code, it seems ok. using a grid search on the set of parameters is also a nice feature, as well as the multiclass setup. but it is misleading to call your function SvmKmeansSimpleLearner, while it actually learns and predicts. a more clear interface, dividing it into train and predict, where the user can divide the data into train and test, would be helpful. 

testing machine learning code is a difficult story. even if you have a nice mathematical proof of say some convergence theory, there is usually no guarantee that it works in your software. for example, SVMperf is one of the best known svm solvers, and is often regarded to be superior to LIBSVM when data sets become very large. unfortunately, you can see SVMperf going 'nuts' on very simple xor like problems. it will also go into some seemingly infinite loop with some parameter settings, regardless of the data set. so the software seems bogus, and it is not fully clear if its the implementation or the algorithm behind it (as O(N^2) does not tell you much about actual runtimes). there are also some discussion about this subject (see for example http://www.reddit.com/r/MachineLearning/comments/2wk8yi/discuss_the_elephant_in_the_room_of_machine/).

nonetheless, usually you would test your algorithm on some small synthetic benchmarks to make sure that in these easy, controlled cases your algorithm behaves as you expect. then you go over to the usual benchmark data sets with various sizes and test your algorithm there, usually to show that your method works better at least on those data  sets you expected to be better than the state-of-art. after that you simply hope for the best (e.g. it helps *not* to publish your code along with the paper ;) yes, i find that not scientific too, but seems pretty normal nowadays).

back to business-- i regret to say that we already have several candidates for the ensemble svm project. to judge if your application make sense, can you give us some link to other R code from you?

**Comment by GANDALF-THEGREY** [comment]
I've implemented an RFLDA (from HiDimDA) learner for mlr and its basic unit test . I might need some comments  the tuning part as it runs into error an on the  tuning in crossvalidation. I have implemented the class predictor for now and will add the functionality for posterior calculation next. The hyperparameter q is not being used as of now.
https://github.com/GANDALF-THEGREY/mlr

**Comment by arinik9** [comment]
@aydindemircioglu 
thanks for your reply! I'll reorganize my code for more clear interface such as the user can divide the data into train and test. Thanks also for the explication detailed for the history of the testing ml algorithms/methods.

The links below are according to my senior project about Complex Network & Community Detection.
The codes didn't sometimes be commented in english. I hope this is not a problem for now, I'll recomment it soon. 

In this project, I've rewrote [Louvain Agorithm](https://github.com/arinik9/graph_theory/blob/master/louvain/louvain.R)  in R and I've extended it for the graphs directed. We are working on the 3 mobile datasets (Nokia & MIT) and we need some further information about edge directions for detect communities. That's why we've focused on the Louvain algorithm. 
In this project, it's required to use the [modularity function](https://github.com/arinik9/graph_theory/blob/master/codes/modularity2_directed.r) for directed graphs.
 
The goal of the project is to detect the communities, to compare the communities computed with ground-truth and to interpret them via Frequent Pattern Mining. 2 functions for the comparison of the communities are [here](https://github.com/arinik9/graph_theory/tree/master/codes/compare).
And 2 functions for drawing are [here](https://github.com/arinik9/graph_theory/tree/master/codes/draw).

I hope that my application seems interesting for the ensemble svm project. If possible, can you explain what skills do you expect  the appplicants in this project? I've discovered SVM via Ng's ML Videos and I'm so motivated for this project. That's why I wanted to add some feature in this demo code.

Thanks.

**Comment by aydindemircioglu** [comment]
@arinik9 



as for the comments, it is a good idea always to use english, even for your personal projects. but please do not mind, i can read them anyway (as you probably guessed from my name).

naturally we are looking for someone who has already worked several years with R, and probably similarly long with machine learning. as this is an ensemble svm project, it is a good idea to have a good grip on svms already. this requirement also stems from the fact that we hope to be as productive as possible in the rather short time frame given by the gsoc program.

from the code you have sent me, i am not sure if you do fit into the above mentioned profile. as we are instructed from the R admins to limit the number of possible participants, and we already have at least two very promising students, with much regret i recommend you to look out for a project which does better match to your skills.

**Comment by luizfox** [comment]
Hi, 

I'm trying to complete the test required for the visualization project. It seems that my examples runs fine, but the CI build failed twice. I run the tests on mlr with devtools's test() function. Got some errors, but none about the code on plotROCRCurves. I think I need additional information about the test process. Where can I find it? My pull request would be considered even if it doesn't say ok on the CI build test?

Thanks.

**Comment by larskotthoff** [comment]
@luizfox I'll comment on your pull request.

**Comment by rishy** [comment]
Hi @berndbischl and @mllg , I have submitted a proposal for "Improving mlr's hyperparameter and tuning system for efficient model selection" at melange, can you guys have a look at it, and provide some feedback about the same?

**Comment by berndbischl** [comment]
GSOC has already begun
