### ISSUE TITLE
Setting rpart options for classif.ada

### ISSUE THREAD

**Issue by phASL** [berndbischl/mlr#254]
Setting rpart options for ```classif.ada``` via ```par.vals``` or directly e.g. as ```maxdepth``` argument is not possible:
```R
library("mlr")

param = list(maxdepth = 5)
lrn.ada = makeLearner("classif.ada", par.vals = param)
train(lrn.ada, sonar.task)
# Error in ada.default(x, y, ..., na.action = na.action) : 
#   Error:  Argument maxdepth not matched

lrn.ada = makeLearner("classif.ada", maxdepth = 5)
train(lrn.ada, sonar.task)
# Error in ada.default(x, y, ..., na.action = na.action) : 
#   Error:  Argument maxdepth not matched
```
You can use a trick: Set the mlr option ```on.par.without.desc``` to "warn" and use the ```...``` argument:

```R
param = list(maxdepth = 5)
# also possible: param = rpart.control(maxdepth = 5)

configureMlr(on.par.without.desc = "warn")
lrn.ada = makeLearner("classif.ada", ... = param)
# Warning message:
# In setHyperPars2.Learner(learner, insert(par.vals, args)) :
# classif.ada: Setting parameter ... without available description object!
# You can switch off this check by using configureMlr!

train(lrn.ada, sonar.task)
# Model for id = classif.ada class = classif.ada
# Trained on obs: 208
# Used features: 60
# Hyperparameters: ...=<list>
```

The problem is that ```ada()``` requires a named list for the rpart options, so I think it's a better solution to insert some code in ```trainLearner.classif.ada```, just like the [ctrl argument] (https://github.com/berndbischl/mlr/blob/0eec258c8b5e39691aeaf229e647ca0796e64435/R/RLearner_classif_boosting.R#L34) in ```trainLearner.classif.boosting```.

**Comment by jakob-r** [comment]
@berndbischl See if you like this (https://github.com/berndbischl/mlr/commit/bc27e5122c8c6eee35818eec8f0a5ffcfe95163f) solution and I will merge it into master branch
