### ISSUE TITLE
Git Workflow

### ISSUE THREAD

**Issue by jakob-r** [berndbischl/mlr#256]
Saw this in the BatchJobs Issue tracker. It also belongs here I guess.
http://nvie.com/posts/a-successful-git-branching-model/

**Comment by berndbischl** [comment]
IMHO this does not belong here.

Why not open a central WIKI page somewhere where we can discuss / doc this? 

Feel free to start this, but close this here.

**Comment by jakob-r** [comment]
Related: https://github.com/blog/1547-release-your-software
