### ISSUE TITLE
Why does mlr need wireless access for checks?

### ISSUE THREAD

**Issue by kerschke** [berndbischl/mlr#261]
I just recognized something, which I thought is very strange: when running the checks of the entire package with internet connection, everything's fine. However, if I am running the checks without wireless access, I get the following error: 

```{r}
* checking tests ...
  Running ‘run-base.R’
 ERROR
Running the tests in ‘tests/run-base.R’ failed.
Last 13 lines of output:
         }
         typeName = gsub("^CURLE_", "", typeName)
         fun = (if (asError) 
             stop
         else warning)
         fun(structure(list(message = msg, call = sys.call()), class = c(typeName, "GenericCurlError", 
             "error", "condition")))
     }(6L, "Could not resolve host: viper.ijs.si", TRUE)
  10: fun(structure(list(message = msg, call = sys.call()), class = c(typeName, "GenericCurlError", 
         "error", "condition")))
  
  Error: Test failures
  Execution halted
make: *** [check] Error 1
```

Is it only me, who encounters those problems?

**Comment by larskotthoff** [comment]
This is because of the tests for Viper charts, see https://github.com/berndbischl/mlr/blob/master/tests/testthat/test_base_plotViperCharts.R. We could try to determine if there's a network connection and if not, skip the test. Not sure if it's worth the effort though.

**Comment by kerschke** [comment]
Ah ok... That sounds reasonable :-)
I think, it's not necessary to check it. I was just curios to find out, what causes that behaviour (or if it was a bug on my computer).
