### ISSUE TITLE
Travis aborts due to dependency on outdated R packages

### ISSUE THREAD

**Issue by kerschke** [berndbischl/mlr#263]
Travis fails to build the package. As far as I understand the problem, it's caused by the fact that ```xgboost``` is not provided any more for R 3.1.3 (i.e., the most recent CRAN version).
Therefore, someone should fix the code, so those "out-dated" packages are automatically installed (if missing) prior to the checks.

**Comment by larskotthoff** [comment]
Huh. http://cran.r-project.org/web/packages/xgboost/index.html suggests that the package is gone for good. I guess we should remove the learner then?

**Comment by kerschke** [comment]
Well, it depends on whether we need an up-to-date version of that package. Otherwise, we could install an old version from the archive, e.g. http://cran.r-project.org/src/contrib/Archive/xgboost/xgboost_0.3-3.tar.gz

**Comment by larskotthoff** [comment]
I don't think that's a good idea. This could break with new versions of R and of course would require the user to install from the archive as well.

**Comment by berndbischl** [comment]
@hetong007 had already told me about this briefly. They need(ed) to fix some stuff for CRAN let, me check now.

**Comment by berndbischl** [comment]
move learner and test to todo-files and make a note here. 
If they need longer we will open up a separate issue, but we need to be able to test now

**Comment by kerschke** [comment]
Ok, I'll integrate it, into my pull request, so you don't have to do it as well..

**Comment by berndbischl** [comment]
No, I am too lazy, will give you push rights. Use them with dilligence.

**Comment by kerschke** [comment]
I think, I still even have those rights ;-)
Just didn't want to mess with your package :)

**Comment by kerschke** [comment]
Well.. I moved all the ```xgboost``` files into the todo directory and also updated the DESCRIPTION.
However, Travis still says that it wants to install ```xgboost``` :-/
Also, when I try to test ```mlr``` locally via ```test_package("mlr")``` it also fails, because it states that the packages ```Rmpi```, ```mlrMBO``` and ```emoa``` are missing (which are actually installed and up-to-date):

```{r}
1. Error: parallel resampling -----------------------------------------------------------------------------------
For parallelStart please install the following packages: Rmpi
1: withCallingHandlers(eval(code, new_test_environment), error = capture_calls)
2: eval(code, new_test_environment)
3: eval(expr, envir, enclos)
4: doit("mpi", as.character(NA)) at test_parallel_all.R:16
5: parallelStart(mode = mode, cpus = 2L, level = level, show.info = FALSE) at test_parallel_all.R:8
6: requirePackages(getExtraPackages(mode), "parallelStart")
7: stopf("For %s please install the following packages: %s", why, ps)
8: stop(obj)

2. Error: parallel tuning ---------------------------------------------------------------------------------------
For parallelStart please install the following packages: Rmpi
1: withCallingHandlers(eval(code, new_test_environment), error = capture_calls)
2: eval(code, new_test_environment)
3: eval(expr, envir, enclos)
4: doit("mpi", as.character(NA)) at test_parallel_all.R:40
5: parallelStart(mode = mode, cpus = 2L, level = level, show.info = FALSE) at test_parallel_all.R:32
6: requirePackages(getExtraPackages(mode), "parallelStart")
7: stopf("For %s please install the following packages: %s", why, ps)
8: stop(obj)

3. Error: parallel featsel --------------------------------------------------------------------------------------
For parallelStart please install the following packages: Rmpi
1: withCallingHandlers(eval(code, new_test_environment), error = capture_calls)
2: eval(code, new_test_environment)
3: eval(expr, envir, enclos)
4: doit("mpi", as.character(NA)) at test_parallel_all.R:63
5: parallelStart(mode = mode, cpus = 2L, level = level, show.info = FALSE) at test_parallel_all.R:55
6: requirePackages(getExtraPackages(mode), "parallelStart")
7: stopf("For %s please install the following packages: %s", why, ps)
8: stop(obj)

4. Error: tuneMBO -----------------------------------------------------------------------------------------------
Please install the following packages: mlrMBO
1: withCallingHandlers(eval(code, new_test_environment), error = capture_calls)
2: eval(code, new_test_environment)
3: eval(expr, envir, enclos)
4: requirePackages("!mlrMBO") at test_tune_tuneMBO.R:8
5: stopf("Please install the following packages: %s", ps)
6: stop(obj)

5. Error: tuneParamsMultiCrit -----------------------------------------------------------------------------------
For tuneParamsMultiCrit please install the following packages: emoa
1: withCallingHandlers(eval(code, new_test_environment), error = capture_calls)
2: eval(code, new_test_environment)
3: eval(expr, envir, enclos)
4: tuneParamsMultiCrit(lrn, binaryclass.task, rdesc, par.set = ps, measures = list(tpr, fpr), control = ctrl) at test_tune_tuneParamsMultiCrit.R:22
5: requirePackages("emoa", why = "tuneParamsMultiCrit", default.method = "load") at /Users/Pascal/Documents/repos/mlr/R/tuneParamsMultiCrit.R:52
6: stopf("For %s please install the following packages: %s", why, ps)
7: stop(obj)

6. Error: tuneParamsMultiCrit works with low number of evals and dependencies -----------------------------------
For tuneParamsMultiCrit please install the following packages: emoa
1: withCallingHandlers(eval(code, new_test_environment), error = capture_calls)
2: eval(code, new_test_environment)
3: eval(expr, envir, enclos)
4: tuneParamsMultiCrit("classif.ksvm", sonar.task, rdesc, par.set = ps, measures = list(tpr, fpr), control = ctrl) at test_tune_tuneParamsMultiCrit.R:55
5: requirePackages("emoa", why = "tuneParamsMultiCrit", default.method = "load") at /Users/Pascal/Documents/repos/mlr/R/tuneParamsMultiCrit.R:52
6: stopf("For %s please install the following packages: %s", why, ps)
7: stop(obj)

7. Error: y imputing works --------------------------------------------------------------------------------------
For tuneParamsMultiCrit please install the following packages: emoa
1: withCallingHandlers(eval(code, new_test_environment), error = capture_calls)
2: eval(code, new_test_environment)
3: eval(expr, envir, enclos)
4: tuneParamsMultiCrit(lrn, binaryclass.task, rdesc, par.set = ps, measures = list(tpr, fpr), control = ctrl) at test_tune_tuneParamsMultiCrit.R:68
5: requirePackages("emoa", why = "tuneParamsMultiCrit", default.method = "load") at /Users/Pascal/Documents/repos/mlr/R/tuneParamsMultiCrit.R:52
6: stopf("For %s please install the following packages: %s", why, ps)
7: stop(obj)

Fehler: Test failures
```

Does anybody have a solution for that? As long as Travis encounters errors on the current ```mlr``` version, it is difficult to figure out if further changes cause new issues.

**Comment by berndbischl** [comment]
> Well.. I moved all the xgboost files into the todo directory and also updated the DESCRIPTION.
> However, Travis still says that it wants to install xgboost :-/

1) travis is now "green"? 

2) I ensured that long logs are always visible now. We had a travis bug, see 
craigcitro/r-travis/issues#150

3) Maybe you forgot to remove the package from SUGGESTS in DESCRIPTION?
You always need to check this, and also in related cases to rebuild the NAMESPACE, related problems occur here, with exports and imports, when eg methods are removed.

**Comment by berndbischl** [comment]
> Also, when I try to test mlr locally via test_package("mlr") it also fails, because it states that the 
> packages Rmpi, mlrMBO and emoa are missing (which are actually installed and up-to-date):

You need to figure this out now. Can you load the packages manually?

**Comment by kerschke** [comment]
> 1) travis is now "green"?

For some reason it looks like it.. However, it also says it fails.

> 2) I ensured that long logs are always visible now. We had a travis bug, see craigcitro/r-travis/issues#150

> 3) Maybe you forgot to remove the package from SUGGESTS in DESCRIPTION?
> You always need to check this, and also in related cases to rebuild the NAMESPACE, related problems occur here, with exports and imports, when eg methods are removed.
 
Nope, I completely removed it from the DESCRIPTION. I didn't rebuild the NAMESPACE as I expected that Travis is rebuilding it anyways.

> You need to figure this out now. Can you load the packages manually?

I can ```install``` it, I can do ```library(mlr)``` and I can also ```load_all(".")```. But still, I can't run the big tests. It's always crashing in the tune tests.

**Comment by kerschke** [comment]
Oh and yes, I can also load and install the other packages manually.

**Comment by kerschke** [comment]
Well, apparently I can only load them manually, if I have a fresh R session. If I do it after trying to run the tests, I get for instance the following error messages: 

```{r}
> library("Rmpi")
Error : .onLoad in loadNamespace() für 'Rmpi' fehlgeschlagen, Details:
  Aufruf: dyn.load(file, DLLpath = DLLpath, ...)
  Fehler: kann shared object '/Library/Frameworks/R.framework/Versions/3.1/Resources/library/Rmpi/libs/Rmpi.so' nicht laden:
  maximale Zahl von DLLs erreicht...
Fehler: Laden von Paket oder Namensraum für ‘Rmpi’ fehlgeschlagen
```

**Comment by kerschke** [comment]
@berndbischl does it run on your computer and/or SLURM? I tried both several times and I'll always get the previously mentioned errors when running the following lines
```{r}
> library(devtools)
> load_all(".")
> library(testthat)
> test_package("mlr")
```
If I then try to load any of those packages, which cause the error (e.g. ```emoa```) -- because R tells me that they are not installed -- I'll get the note that the maximum number of DLLs is reached:

```{r}
> library(emoa)
Error in dyn.load(file, DLLpath = DLLpath, ...) : 
  unable to load shared object '/home/kerschke/R/x86_64-unknown-linux-gnu-library/3.1/emoa/libs/emoa.so':
  `maximal number of DLLs reached...
Error: package or namespace load failed for ‘emoa’
```

Interestingly, if I run the previous test with the argument ```filter = "tune"```, I only receive an error saying that ```mlrMBO``` is not installed (all the other packages then seem to be ok):

```{r}
> test_package("mlr", filter = "tune")
ModelMultiplexer : ...............
tuneCMAES : ......
tuneGrid : ...
tuneIrace : ..........
tuneMBO : Loading required package: mlrMBO
Loading required package: lhs
Failed with error:  ‘cannot open the connection’
In addition: Warning message:
In gzfile(file, "rb") :
  cannot open compressed file '', probable reason 'No such file or directory'
1
tuneParamsMultiCrit : ................
tuneRandom : ......
tuneThreshold : ....


1. Error: tuneMBO --------------------------------------------------------------
Please install the following packages: mlrMBO
1: withCallingHandlers(eval(code, new_test_environment), error = capture_calls)
2: eval(code, new_test_environment)
3: eval(expr, envir, enclos)
4: requirePackages("!mlrMBO") at test_tune_tuneMBO.R:8
5: stopf("Please install the following packages: %s", ps)

Error: Test failures
```

And if I then try to install ```mlrMBO```, I'll get the following error:
```{r}
> install_github("bernbischl/mlrMBO")
Downloading github repo bernbischl/mlrMBO@master
Error in download(dest, src, auth) : client error: (404) Not Found
```
However, I can easily install it prior to those tests (with a fresh R session):
```{r}
> library(devtools)
> install_github("berndbischl/mlrMBO")
Downloading github repo berndbischl/mlrMBO@master
Installing mlrMBO
'/opt/R/R-3.1.2/lib/R/bin/R' --vanilla CMD INSTALL  \
  '/tmp/RtmpwEnSWf/devtools1c3d6fb54b68/berndbischl-mlrMBO-37cdd7a'  \
  --library='/home/kerschke/R/x86_64-unknown-linux-gnu-library/3.1'  \
  --install-tests 

* installing *source* package ‘mlrMBO’ ...
** libs
gcc -std=gnu99 -I/opt/R/R-3.1.2/lib/R/include -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -DVARIANT=4 -c -o avl.o avl.c
gcc -std=gnu99 -I/opt/R/R-3.1.2/lib/R/include -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -DVARIANT=4 -c -o hv.o hv.c
gcc -std=gnu99 -I/opt/R/R-3.1.2/lib/R/include -DNDEBUG  -I/usr/local/include    -fpic  -g -O2  -c infill.c -o infill.o
gcc -std=gnu99 -shared -L/opt/R/R-3.1.2/lib/R/lib -L/usr/local/lib -o mlrMBO.so avl.o hv.o infill.o -L/opt/R/R-3.1.2/lib/R/lib -lR
installing to /home/kerschke/R/x86_64-unknown-linux-gnu-library/3.1/mlrMBO/libs
** R
** inst
** tests
** byte-compile and prepare package for lazy loading
** help
*** installing help indices
** building package indices
** testing if installed package can be loaded
* DONE (mlrMBO)
```

As this error might be related to ```mlrMBO``` (which apparently also does not have a "green light" anymore), could it be that those errors are related and might vanish once someone fixes ```mlrMBO```?

**Comment by berndbischl** [comment]
Pascal, please install dt
then tell  me if you can run
dt test --filter=base
dt check

**Comment by kerschke** [comment]
How can I install it? A note in the dt readme would be helpful :)

**Comment by berndbischl** [comment]
Open up a issue there or better: a pull request.

clone the repo, then put a sym link in your "bin" dir to the "dt" main script, or whatever you do on mac.
then you can call it on the console

**Comment by kerschke** [comment]
Perfect, `dt test --filter=base` and `dt check` run without problems.
Even `dt test --filter=tune` now runs without problems :-)

However, now the tests for classif and regr don't run smoothly any more (even on the repo version from yesterday, which was supposed to be ok).

When testing the regression learners, I got an error that the BostonHousing data set was unknown. After changing ```data(BostonHousing)``` into ```data(BostonHousing, package = "mlbench")``` (within test_regr_randomForest_se.R), that problem was solved as well.

However, when running `dt test --filter=classif` I get another error:
```{r}
1. Failure(@/Users/Pascal/Documents/repos/mlr1/tests/testthat/helper_helpers.R#107): classif_logreg 
p not equal to old.probs
Mean relative difference: 2.830886e-07

2. Failure(@/Users/Pascal/Documents/repos/mlr1/tests/testthat/helper_helpers.R#107): classif_probit 
p not equal to old.probs
Mean relative difference: 6.357676e-07
```

I also checked within those test files and unfortunately, logreg converges only in a few cases, which then again leads to errors when comparing the predicted probabilities..

**Comment by kerschke** [comment]
I think, I finally solved that issue.
Recently, I was following Zachary Mayer's description on how to use Apple's version of BLAS (http://www.stat.cmu.edu/~nmv/2013/07/09/for-faster-r-use-openblas-instead-better-than-atlas-trivial-to-switch-to-on-ubuntu/#comment-86):

> For reference, mac users can use Apple's version of BLAS in the accelerate framework using:
> 
> `cd /Library/Frameworks/R.framework/Resources/lib`
> 
> `ln -sf /System/Library/Frameworks/Accelerate.framework/Frameworks/vecLib.framework/Versions/Current/libBLAS.dylib libRblas.dylib`
> 
> You can go back to the default BLAS using:
> 
> `cd /Library/Frameworks/R.framework/Resources/lib`
> 
> `ln -sf libRblas.0.dylib libRblas.dylib`

However, apparently, this was causing my most recent errors (different predictions for the same models and predictions using logistic regression). After switching back to the default BLAS, this error vanished.. :)

**Comment by mllg** [comment]
1. Are you sure you need a BLAS on your macbook? ;)
2.I've used homebrew to install openblas and R (R should automatically link against openblas if it is installed first)
3. If you're lazy, [Revolution R](http://www.revolutionanalytics.com/community) ships with the intel MKL

**Comment by kerschke** [comment]
1.) No, but I wanted to try it (after I've heard about it from you and Bernd) and as you see - it wasn't a good idea :-)
2. and 3.) Would be options, but for now, I'm postponing my next try with a BLAS :-)
