### ISSUE TITLE
Option for having a formula other than "Y ~ ." 

### ISSUE THREAD

**Issue by rishy** [berndbischl/mlr#266]
A lot of packages like mgcv::gam, neuralnet::neuralnet, etc. don't support formula with a '.' and needs explicitly mentioned predictors as "Y ~ x1 + x2 + x3 + x4". 

We could have such an option in 'mlr' to change the formula as required by these packages. I can start to work on it, if you guys think that it'll be good to have something like this.

**Comment by berndbischl** [comment]
So we would need to improve the helper function getTaskFormula?

Because this would be called in the learner? 

Maybe we just add an argument "explicit.features" there?

**Comment by rishy** [comment]
yeah exactly... that'll do. 
I think I'll get done with this, as soon as possible.

**Comment by kerschke** [comment]
Don't worry, I just integrated it :-)

**Comment by rishy** [comment]
cool.

**Comment by berndbischl** [comment]
Please do not prematurely close this. 
If it is done, pls reference the commit.

And is this used now in some learners?

**Comment by kerschke** [comment]
The commit was referenced above.

**Comment by berndbischl** [comment]
Ah, sorry. 

The code looks in general ok, but:

a) I dislike a bit that the interface of the 2 function is now different. Can we make it more similar?

b) dont we need to use this now for the learners mentioned above?

**Comment by larskotthoff** [comment]
Is there any reason not to make the expanded version without "." the default? That would avoid the issues with having two different versions (and having to maintain them).

**Comment by kerschke** [comment]
> Ah, sorry.
> 
> The code looks in general ok, but:
> 
> a) I dislike a bit that the interface of the 2 function is now different. Can we make it more similar?

Sure, we could just use the explicit.features argument in both versions.

> b) dont we need to use this now for the learners mentioned above?

Correct. But that does not relate to the issue anymore. Instead it rather relates to #257.

> Is there any reason not to make the expanded version without "." the default? That would avoid the issues with having two different versions (and having to maintain them).

Not from my side..

**Comment by berndbischl** [comment]
@larskotthoff 
This would change the code that is run for each learner? Are you sure of the implications also wrt to performance? Also note that the string can become very long for large features....
I have a gut feeling that this will not end well

**Comment by larskotthoff** [comment]
Yes, it would change the code. I don't know about the performance implications, but given that the learner would need to do this expansion internally anyway, I would be surprised if it became much slower.

I see your point about very long strings, but this is also a problem for the learners that do need the expansion, i.e. it's something which needs to be handled correctly anyway.

**Comment by rishy** [comment]
@berndbischl, Sorry for closing the issue. 

I tried using "explicit.features" with mgcv::gam for classification and it worked just fine. I have also sent a PR regarding the same: https://github.com/rishy/mlr/commit/78ef6073ac9f7a496dcff20b96a341f5696397e5

**Comment by berndbischl** [comment]
@kerschke 

"Sure, we could just use the explicit.features argument in both versions."

It would have been nice if you would have responded to this....
Will clean it up now

**Comment by berndbischl** [comment]
We have only option "explicit.features" now. Option "features" in getTaskFormulaAsString was never even used once.

**Comment by kerschke** [comment]
I didn't see (and still don't see) anything that I should respond to.
Based on comments such as "I have a gut feeling that this will not end well" and "who wants to change this should measure it first", I assumed you're not interested in that feature..
