### ISSUE TITLE
Bad design of help page

### ISSUE THREAD

**Issue by IcedragonP** [berndbischl/mlr#268]
Hi, 

the design on 
http://berndbischl.github.io/mlr/tutorial/html/integrated_learners/
is not so good. If I go on this page half of the "note"-column is not visible (only if I scroll), because my screen is not wide enough. On the left side the table of contents takes too much space.

Cheers,
Philipp

**Comment by larskotthoff** [comment]
The minimum system requirement for mlr is a 24" screen :)

But seriously, this has been brought up in #157 already, so I'm tempted to close this as a duplicate. Any objections?

**Comment by berndbischl** [comment]
Cant we simply solve it and delete it from both threads? I didnt look into this, how hard is this?

**Comment by larskotthoff** [comment]
I guess the easiest solution would be to change the theme.

**Comment by berndbischl** [comment]
thats @jakob-r  specialty. do it with minimal effort and it is not top prio.

**Comment by berndbischl** [comment]
@jakob-r ping

**Comment by berndbischl** [comment]
@jakob-r ping

**Comment by jakob-r** [comment]
I already made a research and added my own whishes, including the following options:

1) put the left handed navigation box on top (happens autmatically but too late)
2) make the table headings floating with the scroll to be always visible (highest prio for me)
3) tweak css to make everything smaller

Issues
2) Costumization is hard with what we get from a markdown table
4) It looked quite ok on my 13" notebook

**Comment by jakob-r** [comment]
3. Is done now: 606f060580ff113797b3079db43d44df08b37157

**Comment by berndbischl** [comment]
Ok I will check on my notebook too, if it looks ok i will close
Or do you need to keep this open?

**Comment by larskotthoff** [comment]
Could we not right-align the props and left-align the note? This makes it look a bit squashed. I would left-align the props as all other text is.

**Comment by berndbischl** [comment]
Could we really close this soon?

**Comment by larskotthoff** [comment]
I'm just nitpicking. Closing.
