### ISSUE TITLE
Better Contribution Guidelines for mlr

### ISSUE THREAD

**Issue by rishy** [berndbischl/mlr#270]
I think we can improve a bit more on how we contribute in 'mlr' development work. I think two of the most important things that can be improved are:

- Instead of including multiple commits in a PR, we can ask contributors to squash multiple commits in a single one and then send the PR. This will probably be a much more cleaner way to contribute, where a contributor can merge together all the commits for a specific feature or fix under just a single, well-written commit message.

- We can further create a 'develop' branch, apart from the existing master one, which can be used for all the latest development work. And we can keep 'master' branch aside as our deployment branch. In this way we can keep our not so robust development code in 'develop' branch and deploy-able code in master branch. 

Apart from these we can add some general contribution guidelines in our wiki so as to have a more structured contribution workflow for 'mlr'. I generally prefer using something like this: https://github.com/rishy/sfd-smvdu/blob/develop/README.md. So that new contributors can adhere to the existing workflow in any github repo.

If you guys think that this can be of some help for 'mlr' then I'll quickly add a Wiki for the same.

Thanks

**Comment by larskotthoff** [comment]
Thanks for raising this, I agree that we need to be more clear about how things should be contributed. I also think it's a good idea to have more branches; probably one for each feature.

I don't agree with squashing commits though. I think it's clearer to see how something was developed, and the message for the entire thing can be seen in the respective pull request.

**Comment by rishy** [comment]
Yeah, having multiple branches at least for major features will result in a much more structured contribution, so that people working on a particular feature won't mess with the code of another branch.
 
So maybe I can start with a minimal contribution guidelines wiki and afterwards, you, @berndbischl  and other people may edit it accordingly?

**Comment by larskotthoff** [comment]
That would be very helpful, please do. I would also add more "technical" information, e.g. that you should write tests, how to run the tests and check the package. Assume that the reader doesn't have a strong background in R development.

**Comment by rishy** [comment]
ok. I am on it ;)

**Comment by rishy** [comment]
Hi @larskotthoff, I have added a very basic wiki regarding setup and contribution guidelines here: https://github.com/berndbischl/mlr/wiki/mlr---Setup-and-Contribution-Guidelines. You can further edit it by adding more so called "technical information" :)

**Comment by larskotthoff** [comment]
I've edited a bit and added more technical information -- https://github.com/berndbischl/mlr/wiki/Setup-and-Contribution-Guidelines. Closing this issue for now.
