### ISSUE TITLE
Function messages should not use `cat`, `catf`, `print`

### ISSUE THREAD

**Issue by larskotthoff** [berndbischl/mlr#275]

**Comment by jakob-r** [comment]
We use `cat`, `catf`and `print` (nearly) only in printing methods except `analyzeFeatSelResult` which is purposefully just to give you an text output. Additionally I can't find the recommendation [here](http://cran.r-project.org/doc/manuals/r-release/R-exts.html#Printing) 
However:
removed print from `regr.bcart`, `regr.btgp`, `regr.btgpllm`, `regr.btlm`, `regr.laGP` where it was accidently I guess.
