### ISSUE TITLE
makeDiscreteParam for "ntree", CV for F-racing

### ISSUE THREAD

**Issue by zygmuntz** [berndbischl/mlr#280]
I get the following error when attempting to tune _ntree_ in random forest as a discrete param:

	makeDiscreteParam( "ntree", values = c( 100, 200, 300, 400, 500 ))

	[Tune-x] Setting hyperpars failed: Error in setHyperPars2.Learner(learner$base.learners[[z$ind]], par.vals = setNames(par.vals[i],  : 
	  200 is not feasible for parameter 'ntree'!

Here's my code:

	library( mlr )

	# setwd...

	train = read.csv( 'data/train.csv' )

	data = train[,4:ncol( train )]
	data = data[data$Type != 'DT',]
	data$revenue = log( data$revenue )

	task = makeRegrTask( 'restaurants', data, 'revenue' )

	learners = list(
		makeLearner( "regr.ksvm" ),
		makeLearner( "regr.randomForest" ),
		makeLearner( "regr.lm" )
	)

	multiplexer = makeModelMultiplexer( learners )

	params = makeModelMultiplexerParamSet( multiplexer,
		regr.ksvm = makeParamSet(
			makeNumericParam( "sigma", lower = -12, upper = 12, trafo = function(x) 2^x )
		),
		regr.randomForest = makeParamSet(
			# makeDiscreteParam( "ntree", values = c( 100, 200, 300, 400, 500 ))
			makeIntegerParam( "ntree", lower = 10, upper = 500 )
		)
	)

	resampler = makeResampleDesc( "CV", iters = 5 )

	tuner = makeTuneControlIrace( maxExperiments = 200 )

	res = tuneParams( multiplexer, task, resampler, par.set = params, control = tuner, measures = list( rmse ), show.info = T )

	print( head( as.data.frame( res$opt.path )))

I'm using data from Restaurant Revenue Prediction competition at Kaggle:
http://www.kaggle.com/c/restaurant-revenue-prediction

This set has only ~140 training examples, so I'd like to use CV. Bernd tells me I should use holdout instead, as mlr won't understand CV in this case (with Irace? why?).

**Comment by larskotthoff** [comment]
@zygmuntz Is this issue resolved? Is the error fixed?
