### ISSUE TITLE
parallel has to be loaded to compute rf.importance

### ISSUE THREAD

**Issue by IcedragonP** [berndbischl/mlr#282]
Package parallel is not loaded with mlr Package, but following problem occurs, if you want to compute the randomForest importance...
It only works if parallel is loaded.

> library(mlr)
Lade nötiges Paket: ParamHelpers
Lade nötiges Paket: BBmisc
Lade nötiges Paket: ggplot2
> data(PimaIndiansDiabetes2, package = "mlbench")
> task = makeClassifTask(target = "diabetes", data = PimaIndiansDiabetes2)
> fv = getFilterValues(task, method = "rf.importance")
Error in unlist(mclapply(1:ncol(dat), function(k) { : 
  konnte Funktion "mclapply" nicht finden
> library(parallel)
> fv = getFilterValues(task, method = "rf.importance")
>

**Comment by larskotthoff** [comment]
Works for me using mlr HEAD, R 3.1.0.

**Comment by IcedragonP** [comment]
R 3.2.0, and newest mlr version. (what is HEAD?)

**Comment by larskotthoff** [comment]
The current repository (unreleased) version. Can you try with that one please?

**Comment by larskotthoff** [comment]
Also tested on a fresh install of R-devel with mlr HEAD -- works fine for me. Maybe something in your R configuration?

**Comment by IcedragonP** [comment]
Problem was solved by installing the newest randomForestSRC version. (I had 1.4 installed before)

**Comment by berndbischl** [comment]
The same problem occurs on CRAN. I will need to update the suggested version of randomForestSRC.

Sorry, this was hard to figure out.

**Comment by berndbischl** [comment]
I updated DESCRIPTIOMN

@IcedragonP 

I know this might be hard to check but can you take a look? Maybe unintsalt randomForestSRC and use a too old version? does mlr complain now?

**Comment by berndbischl** [comment]
Does somebody have an idea how we can tell users about this? 

I would be pretty sure that @IcedragonP will not get an informative error now that I have entered the version requirement in DESC. This will very likely only influence the checks and tests on CRAN.

**Comment by mllg** [comment]
Why don't you just declare this in the DESCRIPTION?

**Comment by berndbischl** [comment]
@mllg 
I already did, and this does not help, it only helps autochecks on CRAN.
Please read the thread and the email you are in CC to Uwe.

**Comment by berndbischl** [comment]
@mllg 
I changed the code in BBmisc, can you please reread / confirm that you agree?

**Comment by IcedragonP** [comment]
With randomForestSRC 1.4 and the newest mlr head version still getting the same error.

**Comment by berndbischl** [comment]
@IcedragonP 
Yes that was expected. I guess we manually need to check for the right version when we "require" randomForestSRC in mlr. I am mainly waiting for @mllg to give some feedback on my code for this in BBmisc.

**Comment by mllg** [comment]
Your commit breaks mlr, mlrMBO and parallelMap. You have reordered the args of `requirePackages` and pass `why` unnamed to `requirePackages` in mentioned packages.

**Comment by berndbischl** [comment]
I tried to search for this problem but could not find it. What about the rest? 
Shall we keep it and simply reorder the min.version to a later arg place?

**Comment by berndbischl** [comment]
I am not adding custom code here. Users have to update their packages and it is in DESCRIPTION.
We can talk about this again, when such a problem is reported again
