### ISSUE TITLE
Can't create learners using R 3.2

### ISSUE THREAD

**Issue by kerschke** [berndbischl/mlr#285]
I recently updated my R to version 3.2 and now, I am encountering the following error:

```{r}
> makeLearner("classif.lda")
Error: invalid version specification ‘learner classif.lda’
```

I'm actually quite sure, it can't be a problem of mlr since it worked before the R-update.. However, as I *might* not be the only one, who's encountering those problems, any advice is more than welcome :)
I also tried both current mlr-versions, i.e. version 2.3 (from CRAN) and 2.4 (from github). Does anybody have an idea what's causing the problem -- and how to fix it?
By the way, this issue does not only appear on my Mac, but also when checking code with Travis.

**Comment by mllg** [comment]
This commit causes this: https://github.com/berndbischl/BBmisc/commit/bd21ed7638a49e8258b6e4fb1b7fd03f0eb7ef36

You need to downgrade `BBmisc` or fix mlr so that always named arguments are used in calls to `requirePackages()`.

**Comment by kerschke** [comment]
Thanks for the quick response. This solved the problem :-)
