### ISSUE TITLE
contributor guidelines

### ISSUE THREAD

**Issue by zmjones** [berndbischl/mlr#287]
it would be nice if there were some official contributor guidelines which included expectations about testing and so on.

**Comment by larskotthoff** [comment]
Not sure what you mean. There are the [coding guidelines](https://github.com/berndbischl/mlr/wiki/mlr-Coding-Guidelines) and [setup and contribution guidelines](https://github.com/berndbischl/mlr/wiki/Setup-and-Contribution-Guidelines) already which also cover (at least to some extent) testing.

**Comment by berndbischl** [comment]
Fully agree. 

I wrote this some time ago
https://github.com/berndbischl/mlr/wiki/mlr-Coding-Guidelines

@larskotthoff wrote this
https://github.com/berndbischl/mlr/wiki/Setup-and-Contribution-Guidelines

should we merge it? What is missing?

**Comment by zmjones** [comment]
ah ok i was looking at gh-pages. thanks!

**Comment by berndbischl** [comment]
Should we link this from the first page? And please tell us if info is missing there otherwise please close.
