### ISSUE TITLE
Resampling for Time Series

### ISSUE THREAD

**Issue by rpinsler** [berndbischl/mlr#301]
Hi all,

Is there any support for resampling on time series data, e.g. as provided by caret::createTimeSlices? If not, is there an easy way to extend the framework? 

Best regards,
Robert

**Comment by berndbischl** [comment]
Hi. 

1) We don't have support for this currently. 

2) I once "hacked" a similar time slicing approach together for a project some time ago. It is definitely possible but was never officially integrated into the package until now. 

3) I am sure there would be enough interest by people to have something like this in the package. One mainly needs to create a new task for this and I guess a resampling strategy. It is some work, but doable. I cannot do this myself now, but help / supervise if you would be willing to put some work into this. 

4) I will also make a note now to offer this to a student if somebody is in need for an applied project.

**Comment by rpinsler** [comment]
Okay, thanks. Maybe I'll have a look at it when I have more time.

**Comment by berndbischl** [comment]
Ok + Thx.
Closing for now as this is an obvious extension and on my list anyway

**Comment by berndbischl** [comment]
I guess we had another request in #309

**Comment by rpinsler** [comment]
It would also be helpful to have a holdout variant suitable for time series, e.g. a 2/3 split would partition the data into the first 2/3 and the last 1/3, assuming that the data is ordered by time. Maybe you can add an additional parameter "keep.order" or something for the holdout function?

**Comment by berndbischl** [comment]
Can we the other issue which is open to continue discussing this pls?
I will answer there.
