### ISSUE TITLE
Batch for download statistics

### ISSUE THREAD

**Issue by studerus** [berndbischl/mlr#304]
I suggest to add a download statistics batch from [cranlog](http://cranlogs.r-pkg.org/) to our readme. It would look like this
[![](http://cranlogs.r-pkg.org/badges/mlr)](http://cran.rstudio.com/web/packages/mlr/index.html).

For an applied example, see [https://github.com/sjPlot/sjmisc](https://github.com/sjPlot/sjmisc)

**Comment by larskotthoff** [comment]
Great idea, done!
