### ISSUE TITLE
Do we need the data slot in the prediction object?

### ISSUE THREAD

**Issue by jakob-r** [berndbischl/mlr#306]
In the following scenario
```r
res = resample("classif.knn", task = iris.task, resampling = makeResampleDesc("CV"))
```
the `res$pred$data` does not take so much space. But when doing many experiments this slot consumes much space.
Could it be useful to have an option to leave that slot empty when beeing called by resample?

**Comment by berndbischl** [comment]
Agreed. Just add arg "keep.pred = T/F"? With default = TRUE?

**Comment by berndbischl** [comment]
We should probably also add that arg to "benchmark"?

**Comment by berndbischl** [comment]
@jakob-r 
If you open up the request, please answer after more than 2 weeks
