### ISSUE TITLE
Two (little) critics

### ISSUE THREAD

**Issue by IcedragonP** [berndbischl/mlr#316]
The print method for train is not very understandable for me (see example). 
The output "Model for id = classif.randomForest class = classif.randomForest" is very cryptic.
Why not print the task-id instead of the learner id?

Example:
data(iris)
task = makeClassifTask(id = "tutorial", data = iris[-c(1:10),], target = "Species")
lrn = makeLearner("classif.randomForest")
train(lrn,task)

Furthermore it would be nice to have a overall timeslot in resample for the whole resampling like in train (not only the measure timetrain)

**Comment by berndbischl** [comment]
ad 1) 
"the output "Model for id = classif.randomForest class = classif.randomForest" is very cryptic."

What is so difficult here? Very learner has an id and also a class (very often the same). We print both. 
Better like this 
"Model for learner id = classif.randomForest; class = classif.randomForest" ? 
I can also add a line ala "Trained on task with = iris"

ad 2)
I dont get this. Why not simply use measure timeboth and use "summing" as aggregation? is that not enough?

**Comment by IcedragonP** [comment]
1) Yes would be clearer for me and the task id is probably as interesting as the learner id.

2) Yes you could do this, but it is one step more and the user have to search the timeboth slot. And after 30 min of resampling, while you went eating, you would like to know if it took 15 min or 25 min.

**Comment by jakob-r** [comment]
1) agree, we could add the task.id. learner.id is important as it is more specific than the class. hence we might be able to drop class for readability. If the user went so far to change the lrn.id he should remember what the class of that learner was, no?

2) easily done for the user - I don't see a reason to change code, maybe improve documentation
```r
library(mlr)
lrn = makeLearner("classif.randomForest")
timebothsum = setAggregation(timeboth, aggr = test.sum)
res = resample(lrn, task = iris.task, resampling = makeResampleDesc("CV"), measures = list(acc, timebothsum))
# ...
# [Resample] Result: acc.test.mean=0.96,timeboth.test.sum=0.39
```

**Comment by berndbischl** [comment]
i made the printer better and added the slot runtime to the ResampleResult and its printer
