### ISSUE TITLE
Allow regexp for dropFeatures 

### ISSUE THREAD

**Issue by rpinsler** [berndbischl/mlr#328]
If the number of columns are large (and they follow a certain creation scheme, say, AVG_<Feature>) it becomes infeasible to manually drop features. Hence, it would be nice to be able to specify a regexp to exclude features. 

It may also be convinient to exclude all string features as part of fixup.data during task creation.

I could implement both, if desired.

**Comment by larskotthoff** [comment]
You can do this by passing the feature names to a filtering function (which can be completely arbitrary) and the result on to `dropFeatures()` (this can be done before task creation as well obviously). This is IMHO much more flexible than implementing a particular way of filtering (e.g. you may want to filter on feature type to exclude things that a particular learner doesn't support).

Is this an acceptable solution?

**Comment by berndbischl** [comment]
I guess I agree with Lars here. Isnt that just one line of code?

For the 2nd question:
Can you give an example where a problem might be with the current system / what you really mean?

**Comment by rpinsler** [comment]
In fact, this is what I currently do, Lars (@Bernd: the second question is actually exactly the case where you want to exclude feature types that aren't supported, e.g. strings for classification). I agree that in each case it is just a one-liner, so it's merely a matter of convenience. However, in my case that are pretty common tasks, so I wrote helper functions for it. That's when I became curious if there is some greater demand for it.

If you think the current means are sufficient, just close the issue again.

**Comment by berndbischl** [comment]
@rpinsler 

We are in favor of automating common tasks in ML, that is what mlr is good for. 
Your question, and how you motivated it, therefore make sense!

IMHO:
What describe should happen before you create the task. So on a data.frame. Right?
You want a convenient way to drop columns in a df you dont need. 
dropF currently only works on tasks. 

So it should be S3 and be able to be called on dfs. 

Look at createDummyFeatures for a similar thing and how to do this properly.

If you do a Pull Request I am happy top review it.

There is a larger topic of discussion the background that I would like to discuss with @mllg and @larskotthoff. Because we talked about a similar thing in the past - and IMHO we might have come to the wrong conclusion.

**Comment by berndbischl** [comment]
see #327 for a somehow related issue.

**Comment by berndbischl** [comment]
One comment: 

For stuff like this, it might be good to post how a use-case of your new version might look like. 
So we agree on the signature and so on, BEFORE you waste time to try out something we might not like.

**Comment by rpinsler** [comment]
Yeah, that sounds right. I mean in general it is just a matter of how much preprocessing is necessary until you can throw your data into the framework/a task (handling of missing values being another example). I think mlr is already quite verbose, so I am not sure if such things should be integrated - but that's something you have to decide. 

I'd stick to dropFeatures but extend it for dfs (as in createDummyFeatures) with the following signature: *dropFeatures(task, features, filters)*, where features is either a character (vector) or a regexp and filters is a list of functions applied to each column (the parameter could also be replaced by ...).  You can also add another parameter as.regexp to denote how the character should be interpreted.

I could then do something like this:
dropFeatures(df, features = "ID|_DESC|MAX_", filters = list(is.character, function(x){all(is.na(x))}))

One advantage of applying it to a task is that you can prevent that the target variable is dropped as well, e.g. because it also starts with MAX_. With the current functionality of dropFeatures, I don't see any benefit compared to dropping the features beforehand. It's just another syntax.

**Comment by berndbischl** [comment]
I guess I agree to all I see and we dont complicate things a lot, we just make dropF more useful.

But would it be better to have an extra arg for the regexp? So you dont need to guess what the user meant?

**Comment by larskotthoff** [comment]
Or just have a general filter function argument? The problem I see with allowing regular expressions *and* filter functions is that it's very easy to get confused which is filtering what (and the order of those filters being applied).

**Comment by berndbischl** [comment]
@larskotthoff 
I guess I agree. If you really want both you could just call the functions twice. So "filter" could a string or a  list of functions?

**Comment by larskotthoff** [comment]
Yes, and interpret as a regular expression if a string.

**Comment by rpinsler** [comment]
Alright. I'd still add an argument to denote whether the string should be interpreted as a regexp or not. Furthermore, it should still be possible to pass a character vector, which is independent of whether it is interpreted as a regexp or not.
Then it would look like this:
dropFeatures(obj, filters, as.regexp = FALSE)
obj - data frame or task
filters - list of functions that are applied to each column or character (vector) that is compared to each column name of the data. All columns for which this is true are removed.
as.regexp - if filters is a character (vector), should it be interpreted as a regular expression?

An alternative would be an additional function selectFeatureByName(obj, names, as.regexp) that acts as an own filter function. However, if we just want to remove some features by name (without using regexp), it becomes quite cumbersome: dropFeatures(obj, function(){selectFeaturesByName(obj, "feature")}). 
It might also be convenient to have a reverse argument (= exclude all features except X).

**Comment by berndbischl** [comment]
I dont want to annoyanybody, bit maybe this is easiest

dropFeatures(obj, features, regexp, filters)
features = char vec, names to drop
regexp = what to drop with a regexp 
filters = your functions

Then document that this is applied "from left to right"
It is pretty clear what happens and most user wil only use 1 arg.

**Comment by larskotthoff** [comment]
Given that all strings are also regular expressions, I would combine the `features` and `regexp` arguments.

**Comment by rpinsler** [comment]
I like Bernd's solution. However, the more I think about it the more I believe that maybe this should really be done outside of mlr, especially if we talk about dfs. dplyr::select offers a lot more functionality and flexibility, so it doesn't make sense to copy it. 
What dplyr doesn't have is something like the "filters" argument, where you can pass arbitrary functions. The initial reason why I asked for it was because it always needs some data wrangling to pass the data into a task (no character columns, target column needs to be a factor instead of a plain char). Maybe we can reduce the problem to simplfying this step? As mentioned earlier, we could for example extend the functionality of the fixup.data argument for this.

**Comment by larskotthoff** [comment]
It sounds like you want to be able to filter by type. Should that be supported in a more direct way?

**Comment by berndbischl** [comment]
I dunno, I find this thread a bit confusing, it got very although it seems to me we are discussing a not so difficult issue.

@rpinsler:
Can you please cleary write down what are your usecases? What is bad with the current situation and what would you like to have changed? Try to give all relevant examples.

**Comment by rpinsler** [comment]
Agreed. As I said, there's nothing really wrong with the current situation. It simply annoys me that I have to wrangle data only to be able to put it into an mlr task, but maybe that's just me. I suggest I'll close the thread now until I have found some more example use cases.  
Thanks anyway!

**Comment by berndbischl** [comment]
Hi.

Yes, please get back to us if you find steps you need to do all the time, which the package should automize. Our main criterion is that this generalizes well to other peoples workflow. 

We are happy to discuss stuff that makes ML simpler for people, this is why we wrote this here.
