### ISSUE TITLE
getBMRMeasures

### ISSUE THREAD

**Issue by pfistfl** [berndbischl/mlr#337]
Hey,

There are functions to get task.ids and learner.ids from BenchmarResults,
why is there no getBMRMeasures ? 

I created a function that does it but I think it's rather unelegant and I am also not sure if it will work on any type of BMR.

Also not sure whether it should return a list of the measures or just a character vector of the measureIds.

getBMRMeasures = function(bmr){
  # Get names of measures used
  columns = colnames(getBMRPerformances(bmr,as.df = TRUE))
  measureId = columns[!(columns %in% c("task.id","learner.id","iter"))]
  # Get Objects
  measures = lapply(measureId,FUN = function(x) eval(parse(text = x)))
  return(measures)
}

**Comment by berndbischl** [comment]
I will add getBMRMeasures now, but not your version.
That returns a clean list. Use the internal function measureAggrName to get the longer name with test.mean.mmce.

**Comment by berndbischl** [comment]
I also added getBMRMeasureIds and getBMRLearners.

Please close when you think its ok

**Comment by pfistfl** [comment]
Should work, closed.
