### ISSUE TITLE
We should rename getProbabilities to getPredictionProbabilities

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/mlr#346]
and always use this getClassMember style....

We might leave the first method and deprecate it

**Comment by berndbischl** [comment]
Pls Pls really do not close without adressing all stuff in a issue.
Do we want to deprecate the old function?
We should not "hassle" users too much witgh API changes. 

Comments?

**Comment by berndbischl** [comment]
Oops. You did deprecate it? But then say so in NEWS....

**Comment by jakob-r** [comment]
[I specified the NEWS](https://github.com/berndbischl/mlr/blob/master/NEWS#L11)
What is left to do?

**Comment by berndbischl** [comment]
now that "deprecate" is in there: there is only a typo, it is "and deprecateD"

thx. 

I guess we should even have a "deprecate()" helper function in mlr. 
Very easy to search for it later...
