### ISSUE TITLE
classif.svm: Setting parameter scale without available description object!

### ISSUE THREAD

**Issue by MarkusMG** [berndbischl/mlr#354]
Hello,

is this an issue or not? It may be possible that scaling is switched off and it's up to the user how to scale the data. On the other hand it may be possible that the scale parameter just is missing.

R> lrn <- makeLearner("classif.svm", scale=FALSE)
Loading required namespace: e1071
Error in setHyperPars2.Learner(learner, insert(par.vals, args)) : 
  classif.svm: Setting parameter scale without available description object!
You can switch off this check by using configureMlr!

Best regards 
Markus

**Comment by larskotthoff** [comment]
I've just committed a change that exposes this parameter.

**Comment by berndbischl** [comment]
Lars why is "scale" not tunable?

**Comment by larskotthoff** [comment]
I felt that this is something you'd want to control explicitly. Happy to change if you disagree.

**Comment by berndbischl** [comment]
Well, I would usually set it to SCALE = T, but this is not a purely technical param like "verbose" and it can clearly affect model performance, so some peops might want to tune it.

**Comment by larskotthoff** [comment]
Ok, I'll change that.
