### ISSUE TITLE
Matthews Correlation Coefficient greater than 1?

### ISSUE THREAD

**Issue by kato-m** [berndbischl/mlr#363]
HI,
I've did them experiments using Mathew's Correlation Coefficient for evaluating the results. AFAIK, the MCC ranges from -1 to +1 but the call to mlr::performance returns alues above 1.

```R
library(mlr)
data(Sonar, package = "mlbench")
task <- makeClassifTask(id = "example", data = Sonar, target = "Class")
rdesc <- makeResampleInstance("Holdout", task = task)
clss <- list(rpart="classif.rpart", svm="classif.svm")
lrnrs <- lapply(clss, function(x){makeLearner(x,predict.type="prob")})
models <- lapply(lrnrs, function(x){mlr::train(x,task,subset = unlist(rdesc$train.inds))})
lapply(clss,function(n){performance(pred[[sub("classif.","",n)]], measures = list(auc, mcc,f1, tpr, tnr, timetrain), task, models[[sub("classif.","",n)]])})
mcc
```
Concole output is
```
$rpart
      auc       mcc        f1       tpr       tnr timetrain 
0.7585784 3.0975528 0.7837838 0.8055556 0.7352941 0.0300000 

$svm
      auc       mcc        f1       tpr       tnr timetrain 
0.9509804 4.2836037 0.8115942 0.7777778 0.8529412 0.0600000 

> mcc
Name: Matthews correlation coefficient
Performance measure: mcc
Properties: classif,req.pred,req.truth
Minimize: FALSE
Best: 1; Worst: -1
Aggregated by: test.mean
Note: 
```
According to the confusion matrices
```R
lapply(pred, getConfMatrix)
```
with output
```
$rpart
       predicted
true     M  R -SUM-
  M     30  8     8
  R      8 24     8
  -SUM-  8  8    16

$svm
       predicted
true     M  R -SUM-
  M     31  7     7
  R      7 25     7
  -SUM-  7  7    14
```
I would have expected these values:
```
> (30*24-8*8)/sqrt((30+8)*(30+8)*(24+8)*(24+8))
[1] 0.5394737
> (31*25-7*7)/sqrt((31+7)*(31+7)*(25+7)*(25+7))
[1] 0.5970395
```
Am I doing something wrong or lacking understanding or is this a bug?

**Comment by berndbischl** [comment]
No, this seems to be an extremely annoying "brain fart" in the code. I am now looking really closely at the formula and will write unit tests that this never happens again

**Comment by berndbischl** [comment]
I fixed this now. Sorry. I also found function psych::phi, phi statistics is another name for mcc. 
I now compare against that in a unit test.
I will update on CRAN over the weekend so this problem disappears NOW.

I guess it might also be a good idea to compare our measures against what is calculated in OpenML. 
I will open up a issue for that.
