### ISSUE TITLE
No test for regr.nnet

### ISSUE THREAD

**Issue by mllg** [berndbischl/mlr#377]
This is currently completely missing.

**Comment by berndbischl** [comment]
How about doing this quickly? We need to close some issues. I will do this now.

**Comment by berndbischl** [comment]
Why is there a "regr" test in test_classif_nnet?

**Comment by berndbischl** [comment]
Because you ran vim regexp substitute over it ? Looks like it. 
PLEASE look at diffs, ESPECIALLY after you do stuff like this.

**Comment by berndbischl** [comment]
You also have global "debug assignments" in there.... argh.

**Comment by berndbischl** [comment]
I am looking at the diff now. please DO NOT change this now, I will

**Comment by berndbischl** [comment]
You also did not mention that you made an API chnage in NEWS. you removed getTaskFormulaAsString

**Comment by berndbischl** [comment]
I repaired this now. Please at least check. I will now add the unit test for regr nnet

**Comment by berndbischl** [comment]
added a test, please close when you have recheck my manual revert of your stuff

**Comment by mllg** [comment]
Sorry, was in a hurry to get the train ..

**Comment by mllg** [comment]
Reviewed. All good.
