### ISSUE TITLE
Can't load package, because maximum number of DLLs is reached

### ISSUE THREAD

**Issue by kerschke** [berndbischl/mlr#382]
This issue is not necessarily directly related to mlr, but it would make my life a lot easier, if you have any ideas on how to solve it.
When running the tests, e.g. via calling `dt test`, I used to get the error that I reached the maximum number of DLLs and therefore cannot load a certain package. Therefore, I decided to run the tests only on the subgroups, e.g. `dt test --filter="base"` and so on.
However, since today, even that is not working anymore. Now, a lot of tests within that subgroup already fail if I run that subgroup call. If I test the files on their own, everything runs smooth..

Any ideas, how I could fix that?!

**Comment by berndbischl** [comment]
You cannot fix that, that just sucks in R. But you should NOT get this porblem if you simply test with "base". Are you sure that happens?

**Comment by berndbischl** [comment]
"base" runs fine for me. all of the packages get loaded in "classif" and "regr" and so on. 
Can you pls paste where this happens?

**Comment by berndbischl** [comment]
Great now we get the DLL errors on travis. I have no idea what to do. I hate R.
It sucks.

**Comment by kerschke** [comment]
So it's not solely a problem with my computer? Great :)

**Comment by berndbischl** [comment]
I SHOULD NOT happen in base. If you run it locally. Pls paste that. I cannot believe that.

**Comment by kerschke** [comment]
It states more or less the same as the check in the PR does. I just left the office, so I can post it later this evening.

**Comment by berndbischl** [comment]
Solution is in the other thread. Its your new test.

**Comment by kerschke** [comment]
As already mentioned - the solution is in the thread of my previous pull request (#383).

**Comment by owjay** [comment]
{pcal<-princomp(x,scores=T,cor=T)
Error in eigen(cv, symmetric = TRUE) : LAPACK routines cannot be loaded
In addition: Warning message:
In eigen(cv, symmetric = TRUE) :
  unable to load shared object 'C:/PROGRA~1/R/R-31~1.3/modules/x64/lapack.dll':
  `maximal number of DLLs reached...}
what is wrong here?

**Comment by berndbischl** [comment]
@owjay 
we have no chance to answer you if you dont produce a fully reproducible example.

also note that this issue here is closed and will therefore be not on our "radar" very soon

**Comment by owjay** [comment]
this is an r issue that i am requesting for assistance when i try to run principal component analysis, where the rstudio response to "pcal<-princomp(x,scores=T,cor=T)"

is

Error in eigen(cv, symmetric = TRUE) : LAPACK routines cannot be loaded
In addition: Warning message:
In eigen(cv, symmetric = TRUE) :
unable to load shared object 'C:/PROGRA~1/R/R-31~1.3/modules/x64/lapack.dll':
`maximal number of DLLs reached...}

**Comment by berndbischl** [comment]
you do realize that this is the mlr issue tracker? and you have not posted any code from mlr?

**Comment by berndbischl** [comment]
and your code is not reproducible, as x is not defined.

**Comment by owjay** [comment]
thanks. for the feedback

**Comment by berndbischl** [comment]
owjay, here is some background info: 

1) R has the annoying problem that you cannot load more than 100 DLLs. This is something nobody can do anything about.

2) That problem occurs, e.g, if you construct all mlr learners. Because these load extremely many packages and DLLs

3) We triggered that problem in our unit tests, but invested lots of hours to work around that.

4) IMHO in realistic, normal situations this does never occur as you either
a) only use a bunch of well selected learners in a single session, so maybe 10
b) you run benchmarking on all learners, on a cluster, but in that case you likely have individual R sessions on slaves where each one again does only create 1 or a few learners and not all.

5) Now, what happens in your case I cannot say, as you dont follow proper posting guide lines for issue report (sorry...)

Maybe read a page like this?
http://www.chiark.greenend.org.uk/~sgtatham/bugs.html

**Comment by owjay** [comment]
Appreciated bigtime,helped on the 10learners at a time

regards
Jesse

On 9/6/16, Bernd Bischl <notifications@github.com> wrote:
> owjay, here is some background info:
>
> 1) R has the annoying problem that you cannot load more than 100 DLLs. This
> is something nobody can do anything about.
>
> 2) That problem occurs, e.g, if you construct all mlr learners. Because
> these load extremely many packages and DLLs
>
> 3) We triggered that problem in our unit tests, but invested lots of hours
> to work around that.
>
> 4) IMHO in realistic, normal situations this does never occur as you either
> a) only use a bunch of well selected learners in a single session, so maybe
> 10
> b) you run benchmarking on all learners, on a cluster, but in that case you
> likely have individual R sessions on slaves where each one again does only
> create 1 or a few learners and not all.
>
> 5) Now, what happens in your case I cannot say, as you dont follow proper
> posting guide lines for issue report (sorry...)
>
> Maybe read a page like this?
> http://www.chiark.greenend.org.uk/~sgtatham/bugs.html
>
> --
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/mlr-org/mlr/issues/382#issuecomment-244888533


-- 
Regards,
Jesse

**Comment by berndbischl** [comment]
i guess we need an FAQ at some point, and this should be in there
