### ISSUE TITLE
add function to produce a learning curve

### ISSUE THREAD

**Issue by berndbischl** [berndbischl/mlr#68]

**Comment by jakob-r** [comment]
So it works again now.
* uses downsample wrapper and `benchmark()`
* thus can be noisy (perc = 0.1 is not a subset of perc = 0.2)
Please have a look and say what you dis/like.

**Comment by berndbischl** [comment]
Ok I cleaned it up:

- read
- improve what you still see
- doc
- unit test
- example
- tutorial

lets close this soon please

**Comment by jakob-r** [comment]
Left to do is
 * tutorial

**Comment by berndbischl** [comment]
* describe the sampling a bit more and that benchmark is called internally 
* ggplot2 is imported by mlr anyway, dont require it
* plyr2 we should move to imports, I guess

**Comment by berndbischl** [comment]
@jakob-r 
I removed this + test to todo-files as you did not respond.

Please finish soon

**Comment by berndbischl** [comment]
Please mention in NEWS

**Comment by berndbischl** [comment]
From the documentation it is unclear what actually happens. Please fix.

**Comment by berndbischl** [comment]
@jakob-r 
ping

**Comment by jakob-r** [comment]
I think documentation and tutorial give enough information now.

**Comment by berndbischl** [comment]
Thx
